Import('env')

files = [
    'CoarseCC.h',
    'CoarseCCatIntervals.h',
    'CoarseConvolution.h',
    'DensityHeader.h',
    'DensityMap.h',
    'masking.h',
    'EMReaderWriter.h',
    'FitRestraint.h',
    'Image.h',
    'ImageHeader.h',
    'ImageReaderWriter.h',
    'KernelParameters.h',
    'MRCReaderWriter.h',
    'MapReaderWriter.h',
    'SampledDensityMap.h',
    'SpiderHeader.h',
    'SpiderReaderWriter.h',
    'SurfaceShellDensityMap.h',
    'Voxel.h',
    'XplorReaderWriter.h',
    'converters.h',
    'def.h',
    'envelope_penetration.h',
    'exp.h',
    'filters.h',
    'header_converters.h',
    'noise.h',
    'rigid_fitting.h',
    'image_transformations.h' ,
        ]\
+SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
