Import('env')

files = [
         'CoarseCC.h',
         'CoarseCCatIntervals.h',
         'CoarseConvolution.h',
         'DensityHeader.h',
         'DensityMap.h',
         'EMReaderWriter.h',
         'ErrorHandling.h',
         'EulerOperations.h',
         'FitRestraint.h',
         'IMPParticlesAccessPoint.h',
         'Image.h',
         'ImageHeader.h',
         'ImageReaderWriter.h',
         'KernelParameters.h',
         'MRCReaderWriter.h',
         'MapReaderWriter.h',
         'ParticlesAccessPoint.h',
         'SampledDensityMap.h',
         'SpiderHeader.h',
         'SpiderReaderWriter.h',
         'SurfaceShellDensityMap.h',
         'Vector3.h',
         'Volume.h',
         'XplorReaderWriter.h',
         'converters.h',
         'def.h',
         'exp.h',
         'header_converters.h',
         'noise.h',
         'project.h',
        ]

# Install the include files:
env.IMPHeaders(files)
