Import('env')

files = [
         'EMFitRestraint.h',
         'EMnoise.h',
         'EulerOperations.h',
         'IMPParticlesAccessPoint.h',
         'ImageEM.h',
         'ImageHeader.h',
         'VolumeEM.h',
         'endian.h',
         'convertors.h',
        ]

# Install the include files:
env.IMPHeaders(files)
