Import('env')
import scons_tools.examples

env= env.IMPSystem(version='1.0',
                   required_modules=['core', 'atom', 'em2d', 'em'],
                   last_imp_version="""None""",
                   # this is true if the scripts can be run incompletely as test cases
                   # eg if it works to do "sample_0.py 1 1000" and then "analyze_0.py"
                   # without doing all of the sampling required. This can be implementedf
                   # either by providing intermediate data or by only analyzing the data
                   # that happens to be there
                   testable=False, parallelizable=True)
