import os.path
Import('env')

files = ['VRMLLogOptimizerState.h', 'CMMLogOptimizerState.h',
         'VelocityScalingOptimizerState.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'optimizers', 'states')
inst = env.Install(includedir, files)
env.Alias('install', inst)
