Import('env')

files = [
         'KMCenters.cpp',
         'KMCentersNode.cpp',
         'KMCentersNodeLeaf.cpp',
         'KMCentersNodeSplit.cpp',
         'KMCentersTree.cpp',
         'KMData.cpp',
         'KMFilterCenters.cpp',
         'KMLProxy.cpp',
         'KMLocalSearch.cpp',
         'KMLocalSearchLloyd.cpp',
         'KMRectangle.cpp',
         'PartitionalClustering.cpp',
         'point_clustering.cpp',
        ]

# Build and install the shared library:
env.IMPModuleLib(files)
