Import('env')

files = [
         'Histogram.cpp',
         'PartitionalClustering.cpp',
         'metric_clustering.cpp',
         'point_clustering.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
env.IMPModuleLib(files)
