Import('env')

# This finds all python files matching test_*.py and all cpp files
# matching test_*.cpp
env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  spelling_exceptions=['pdb','matlab'],
                  show_exceptions=["ResultAlign2D",
                                    "pair_cluster_id_distance",
                                    "VectorOfFloats"],
                  function_name_exceptions=[
                     'VectorOfFloats.append', 'VectorOfFloats.assign',
                     'VectorOfFloats.back', 'VectorOfFloats.begin',
                     'VectorOfFloats.capacity', 'VectorOfFloats.empty',
                     'VectorOfFloats.end', 'VectorOfFloats.erase',
                     'VectorOfFloats.front', 'VectorOfFloats.insert',
                     'VectorOfFloats.iterator', 'VectorOfFloats.rbegin',
                     'VectorOfFloats.rend', 'VectorOfFloats.resize',
                     'VectorOfFloats.size', 'VectorOfFloats.swap'],
                  value_object_exceptions=["Pixel",
                                          "ResultAlign2D",
                                          "pair_cluster_id_distance",
                                          "VectorOfFloats",
                                          "VectorOfInts",
                                          ])
