Import('env')

# This finds all python files matching test_*.py and all cpp files
# matching test_*.cpp
env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  function_name_exceptions=[],
                  show_exceptions=["ResultAlign2D" ],
                  value_object_exceptions=["Pixel",
                                           "ResultAlign2D",
                                           "ImageReaderWriter",
                                           "JPGImageReaderWriter",
                                           "SpiderImageReaderWriter",
                                           "TIFFImageReaderWriter"
                                           ] )
