/**
 *  \file InContainerPairFilter.h    \brief A filter for particle_pairs.
 *
 *  This file is generated by a script (core/tools/make-containers).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 Sali Lab. All rights reserved.
 */

#ifndef IMPCONTAINER_IN_CONTAINER_PAIR_FILTER_H
#define IMPCONTAINER_IN_CONTAINER_PAIR_FILTER_H

#include "container_config.h"
#include <IMP/PairFilter.h>
#include <IMP/PairContainer.h>

IMPCONTAINER_BEGIN_NAMESPACE


//! A filter which returns true if a container containers the ParticlePair
/** Stores a searchable shared collection of particle_pairs.
    \ingroup restraints

    Implementors should see IMP_PAIR_FILTER().
 */
class IMPCONTAINEREXPORT InContainerPairFilter : public PairFilter
{
  IMP::internal::OwnerPointer<PairContainer> c_;
public:
  InContainerPairFilter(PairContainer *c,
                             std::string name="PairFilter %1%");

  IMP_PAIR_FILTER(InContainerPairFilter);
};

inline bool InContainerPairFilter
::get_contains_particle_pair(const ParticlePair& p) const {
  return c_->get_contains_particle_pair(p);
}

IMP_OBJECTS(InContainerPairFilter, InContainerPairFilters);

IMPCONTAINER_END_NAMESPACE

#endif  /* IMPCONTAINER_IN_CONTAINER_PAIR_FILTER_H */
