/**
 *  \file MaximumPairScore.h    \brief Define PairScore.
 *
 *  This file is generated by a script (tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 Sali Lab. All rights reserved.
 */

#ifndef IMPCONTAINER_MAXIMUM_PAIR_SCORE_H
#define IMPCONTAINER_MAXIMUM_PAIR_SCORE_H

#include "config.h"
#include <IMP/PairScore.h>

IMPCONTAINER_BEGIN_NAMESPACE

//! Evaluate the maximum n pair scores of the passed set of PairScores
/** Each of the set of PairScores is evaluated and the sum of the
    minimum n is returned.
*/
class IMPCONTAINEREXPORT MaximumPairScore : public PairScore
{
  PairScores scores_;
  unsigned int n_;
public:
  MaximumPairScore(const PairScoresTemp &scores,
                       unsigned int n=1,
                       std::string name="PairScore %1%");
  IMP_PAIR_SCORE(MaximumPairScore, get_module_version_info());
};

IMPCONTAINER_END_NAMESPACE

#endif  /* IMPCONTAINER_MAXIMUM_PAIR_SCORE_H */
