Import('env')
import scons_tools.checks

scons_tools.checks.add_external_library(env, "Bullet", ["BulletDynamics", "BulletCollision",
                                                        "BulletSoftBody",
                                                        "LinearMath"],
                                       "btBulletDynamicsCommon.h",
                                        body="""btBroadphaseInterface* broadphase = new btDbvtBroadphase();""",
                                        extra_libs=[])


env.IMPModuleBuild(version='SVN',
                   required_modules=['container', 'cgal'],
                   optional_modules=[],
                   lib_only_required_modules=['atom'],
                   required_dependencies=["Bullet"])
