Import('env')
import scons_tools.dependency
import scons_tools.bug_fixes

scons_tools.dependency.add_external_library(env, "Bullet", ["BulletDynamics", "BulletCollision",
                                                        "BulletSoftBody",
                                                        "LinearMath"],
                                       "btBulletDynamicsCommon.h",
                                        body="""btBroadphaseInterface* broadphase = new btDbvtBroadphase();""",
                                        extra_libs=[],
                                            versionheader="LinearMath/btScalar.h",
                                            versioncpp=["BT_BULLET_VERSION"])


env.IMPModuleBuild(version='SVN',
                   required_modules=['container', 'display'],
                   optional_modules=['cgal'],
                   lib_only_required_modules=['atom', 'domino'],
                   required_dependencies=["Bullet"])
