Import('env')
Export('env')

# No dependent libraries, so this module can always be built:
env.validate()

# Subdirectories:
lib = SConscript('src/SConscript')
SConscript('include/SConscript')
pyext = SConscript('pyext/SConscript')
test = SConscript('test/SConscript')

Return('lib')
