Import('env')
Export('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='Miscellaneous and/or experimental features.')

# No dependent libraries, so this module can always be built:
env.validate()

env.Append(LIBS=['imp_core'])

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
