Import('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='Miscellaneous and/or experimental features.')

# No dependent libraries, so this module can always be built:
env.validate()

env.Append(LIBS=['imp_core', 'imp_atom', 'imp_algebra'])

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
