files = [
         'bond_graph_boost_functions.h',
         'bond_graph_functors.h',
         'bond_helpers.h',
         'mol2.h',
         'pdb.h',
        ]

files = [File(x) for x in files]
Return('files')
