Import('env')

files = [
         'DiscreteSampler.h',
         'CombState.h',
         'combination.hpp',
         'DominoOptimizer.h',
         'JEdge.h',
         'JNode.h',
         'RestraintGraph.h',
         'DiscreteSet.h',
         'TransformationDiscreteSet.h',
         'PermutationSampler.h',
         'MappedDiscreteSet.h',
         'CartesianProductSampler.h',
         'TransformationUtils.h',
         'TransformationMappedDiscreteSet.h',
         'TransformationCartesianProductSampler.h',
         'TransformationPermutationSampler.h',
         'SimpleDiscreteRestraint.h',
         'SimpleDiscreteSpace.h',
         'SimpleDiscreteSampler.h',
         'SymmetrySampler.h'
        ]

# Install the include files:
env.IMPHeaders(files)
