Import('env')

files = [
         'DiscreteSampler.h',
         'CombState.h',
         'DominoOptimizer.h',
         'JEdge.h',
         'JNode.h',
         'RestraintGraph.h',
         'DiscreteSet.h',
         'PermutationSampler.h',
         'SimpleDiscreteRestraint.h',
         'SimpleDiscreteSpace.h',
         'SimpleDiscreteSampler.h',
        ]

# Install the include files:
env.IMPHeaders(files)
