Import('env')

files = [
         'Assignment.h',
         'BranchAndBoundSampler.h',
         'DependencyScoreState.h',
         'DiscreteSampler.h',
         'DominoSampler.h',
         'Subset.h',
         'analysis.h',
         'assignment_tables.h',
         'domino_macros.h',
         'optimize_restraints.h',
         'particle_states.h',
         'subset_filters.h',
         'HeapAssignmentContainer.h',
         'subset_graphs.h',
         'analysis.h',
         'utility.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
