files = [
         'bounding_sphere.h',
         'knn.h',
         'polygons.h',
         'polyhedrons.h',
         'sphere_cover.h',
         'union_of_balls.h',
        ]

files = [File(x) for x in files]
Return('files')
