Import('env')
import scons_tools.dependency.boost
scons_tools.dependency.boost.add_boost_library(env, "ProgramOptions", "program_options", 'boost/program_options.hpp',
                                               extra_boost_libs=["system"])


env= env.IMPApplication(required_modules=['atom'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="pdb_check", source=["pdb_check.cpp"])
    env.IMPCPPExecutable(target="pdb_display", source=["pdb_display.cpp"])
