Import('env')

import os.path

dox = env.Doxygen("doxygen.conf")

docdir = env['docdir']

# Install all files from 'dox' directory into the 'docdir' directory (cannot
# use env.InstallAs() right now, due to scons bug #1751)
env.Command(Dir(env.subst(docdir)), dox,
            "install -d $TARGET && install $SOURCE/* $TARGET",
            source_scanner=DirScanner)
env.Alias('docinstall', docdir)
