Import('env')

env= env.IMPApplication(name="EMageFit",
                        authors=["Javier Velazquez-Muriel"],
                        brief="Modeling of macromolecular assemblies base on EM images",
                        overview="""

This application presents a method to use EM images as restraints for integrative modeling.
It is composed of the EM2DRestraint tha scores the similarity of the projections of a model to
the available EM images, and a sampling algorithm based on Monte Carlo optimization followed by
the application of DOMINO.

There are 4 main executables:

\par emagefit_score.py : Scores a model against ase of EM images. Note: Disregard the deprecated em2d_score executable

\par emagefit.py: The main program for generating models.

\par emagefit_cluster.py: Clusters the models obtained from emagefit.py

\par emagefit_dock.py: Interface between the EMageFit application and the docking program HEXDOCK.
The use of this program is optional. Read the manual for details.

And a simple script to convert between image formats: convert_spider_to_jpg.py

An extensive manual together with an example can can be found in the file MANUAL.pdf EMageFit application directory.
""",

license=env.IMPStandardLicense(),
publications=[env.IMPPublication(authors=["Javier A. Velazquez-Muriel","Keren Lasker", "Daniel Russel",
                                                       "Jeremy Phillips",  "Benjamin M. Webb", "Dina Scheidmann", "Andrej Sali"],
                                                    title="Assembly of macromolecular complexes by satisfaciton of spatial restraints from electron microscopy images",
                                                    journal="under review",
                                                    year=2012,
                                                    url="")],
                        required_modules=["container","core","atom","algebra",
                                      "em","display","gsl","domino","em2d"],
                        required_dependencies=[])
if env:
    env.IMPPythonExecutable('emagefit.py')
    env.IMPPythonExecutable('emagefit_cluster.py')
    env.IMPPythonExecutable('emagefit_score.py')
    env.IMPPythonExecutable('emagefit_dock.py')
    env.IMPPythonExecutable('convert_spider_to_jpg.py')
