Import('env')

env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  show_exceptions=['AllMol2Selector', 'AllPDBSelector',
                                   'ChainPDBSelector',
                                   'ElementTable', 'HierarchyVector', 'HydrogenPDBSelector',
                                   'Mol2Selector', 'NonAlternativePDBSelector',
                                   'NonWaterNonHydrogenPDBSelector',
                                   'NonWaterPDBSelector', 'NonhydrogenMol2Selector','WaterPDBSelector',
                                   'AndPDBSelector', 'OrPDBSelector'])
