Import('env')


env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  show_exceptions=['AllMol2Selector', 'AllPDBSelector',
                                   'ChainPDBSelector',
                                   'ElementTable', 'HierarchyVector'],
                  value_object_exceptions=['ElementTable'],
                  function_name_exceptions=['transform', 'BrownianDynamics.simulate', 'MolecularDynamics.assign_velocities', 'VelocityScalingOptimizerState.rescale_velocities', 'get_all_atom_CHARMM_parameters', 'get_heavy_atom_CHARMM_parameters'],
                  spelling_exceptions=['lennard', 'charmm', "jones", "impropers",
                                       "rmsd", "pdb", "multimodel", "conect"])
