Import('env')

# This finds all python files matching test_*.py and all cpp files
# matching test_*.cpp
env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests())
