import os.path
Import('env')

files = ['ConjugateGradients.h', 'SteepestDescent.h', 'MolecularDynamics.h',
         'MoverBase.h', 'MonteCarlo.h', 'Mover.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'optimizers')
inst = env.Install(includedir, files)
env.Alias('install', inst)
SConscript('states/SConscript')
SConscript('movers/SConscript')
