Import('env')
e = env.IMPSharedLibraryEnvironment()
ns= Glob("*.cpp")+ Glob("*/*.cpp")

files=[]
for h in ns:
    s= h.rstr()
    if not s.startswith(".") and not s.endswith("modulename_version_info.cpp"):
        files.append(s)

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
