Import('env')

# All .dox, .pdf and .pdb files are installed
license_string =  env.IMPStandardLicense() + \
               """ ; \\external{http://www.gnu.org/copyleft/gpl.html,GNU General Public License (GPL)}
                   for the internal library code itself (in the include/internal and src/internal folders).
               """
env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 # A python list of the author names
                 authors=["Barak Raveh"],
                 # Provide a brief description of what the module does
                 brief="This module provides an interface to the GPL k-means clustering open source library in http://www.cs.umd.edu/~mount/Projects/KMeans/",
                 # Provide a longer description of what the module does
                 # This description can have multiple paragraphs and all sorts of markup
                 overview="""This module allows clustering of multi-dimensional data points using the k-menas algorithms, based on the GPL
                 kmeans library in http://www.cd.umd.edu/~mount/Projects/KMeans/""",
                 # IMPPublications can be added using the env.IMPPublication() function
                 # The result should be a python list
                 # env.IMPStandardPublications() defines the general IMP publications
                 #              publications=env.IMPStandardPublications()\
                 #    + [env.IMPPublication(authors=["Some Person", "Someone Else"],
                 #                       title="A silly title of no paper",
                 #                       journal="Dev Null", year=2051),
                 #       env.IMPWebsite(url="http://www.salilab.org/imp", name="IMP")],
                 # License can be either env.IMPStandardLicense() to be the same as the rest of IMP
                 # or it can be a string describing the license, such as "GPL".
                 license=license_string )
