Import('env')

overview="""

\\namespace RMF

The library provides support for the \\ref rmf "RMF"
file format for storing
hierarchical molecular data (such as atomic or coarse
grained representations of proteins), along with
markup, including geometry and score data.

The library uses the \\external{http://www.hdf5.org,HDF5} library to manage the data on
disk. Other backends (eg mmCIF) could be used, if desired.

See \\ref rmf "RMF file format" for more information about the files,
 \\ref rmflib "RMF Library" for more information about using the library and
\\ref categories "RMF data categories" for standard data.



"""
env.IMPModuleDoc(authors=["Daniel Russel"],
                 brief="This module provides %RMF I/O",
                 overview=overview,
                 publications=env.IMPStandardPublications(),
                 files=["3U7W.hdf5.txt", "3U7W.xml", "simple.hdf5.txt",
                        "simple.xml", "3U7W.pdb.txt", "simple.pdb.txt",
                        "categories.dox", "rmf.dox", "types.dox"],
                 license=env.IMPStandardLicense())
