Import('env')

overview="""

\\namespace RMF

The library provides support for the \\ref rmf "RMF"
file format for storing
hierarchical molecular data (such as atomic or coarse
grained representations of proteins), along with
markup, including geometry and score data.

The library uses the \\external{http://www.hdf5.org,HDF5} library to manage the data on
disk. Other backends (eg mmCIF) could be used, if desired.

See \\ref rmf "RMF file format" for more information about the files and
\\ref categories "RMF data categories" for standard data.


\\section lib The RMF library

The %RMF library provides an intermediate level interface to facilitate I/O of
%RMF data into and out of programs. The primary classes of interest are
RMF::RootHandle representing the root of an %RMF hierarchy and RMF::NodeHandle
representing a node in the hierarchy.

The file is automatically closed when the last handle to it is destroyed.

\\subsection basics 0 Basics

The library defines many classes, some of which are implemented using \c C++
templates. Every class support output to a \c std::ostream in \c C++ and
conversion to \c str in \c Python. In addition, every class can be compared
to other instances of the same class and can be inserted in hash tables both
in \c C++ and \c Python. The methods necessary to support these things are
omitted for brevity.

Template classes are, in general parameterized by one of two things
- Arity, meaning whether they relate to a single node, a pair of nodes etc
- type, meaning whether they relate to \\ref rmf_types "integers, floats etc"
For any class that is parameterized by Arity, typedefs (and \c Python types)
are provided for 1 through 4 nodes, with names like \c Category, \c PairCategory,
\c TripletCategory, \c QuadCategory. For classes parameterized by type, typedefs
and \c Python classes are provides for all the \\ref rmf_types "standard types"
with names like \c IntKey, \c FloatKey etc. Some classes, like Key are parameterized
by both, so the full cross product of types is provided with names like
\c PairFloatKey.

In addition, there is a typedef for each type for managing lists of the objects.
For example, a list of \c Category objects is passed using a \c Categories type.
It looks like a \c std::vector in \c C++ and is a \c list in \c Python.

\\subsection assoc 1 Associations

The %RMF wrapper has the concept of an association between nodes in
its hierarchy and objects in the program accessing. The methods
RMF::RootHandle::get_node_handle_from_association(),
RMF::NodeHandle::set_association() and
RMF::NodeHandle::get_assocation() can be used to take advantage of
this. The idea is that one can store pointers to the programatic
data structures corresponding to the nodes and so avoid maintaining
ones own lookup table.

\\subsection accelerating 2 Accelerated I/O

Traversing large %RMF files can be slow, especially when doing so in scripting
languages. The library provides a few methods RMF::get_values() to accelerate
this process when loading values for each of a number of frames. Other such
batch methods can be added as appropriate.

\\subsection parallel 3 Parallel I/O

If RMF::RootHandle::flush() has been called since the last change, it is safe
to read the file from another process. Writing from more than one process is not
supported. Nor is reading or writing from more than one thread of the same
program.

\\subsection invariants 4 Invariants

Currently, there is little explicit checking of invariants between attributes
in the %RMF file. An extensible framework for checking invariants on file
close and open will be added.


\\subsection bindings 5 Other language bindings

The %RMF library currently supports C++ and Python. The API is
written so that \\external{http://www.swig.org,SWIG} can be used to
easily generate bindings for most languages. The two main
exceptions are C and Fortran. Until the SWIG C target support is
finished, these can be supported by writing a simple C API
manually, probably a weeks work.

\\subsection hdf5access 6 HDF5 wrappers

The library provides a simple wrapper for the \C HDF5 library through
the HDF5Group, HDF5DataSetD, HDF5File and helper classes.

\\section bins Helper programs

   - \c rmf_show prints out the hierarchy written to the file.

   - \c rmf_pdb converts an rmf file to or from a PDB file, assuming all hierarchies
   in the rmf file are atomic resolution.

   - \c rmf_xml converts an rmf file to an XML files that can be opened in an XML viewer
   (eg Google Chrome or Firefox). These viewers support collapsing of subtrees, which
   makes it much easier to get around large hierarchies.

See the \\ref application_rmf_tools "RMF tools" application for
\\imp-related helper programs.

"""
env.IMPModuleDoc(authors=["Daniel Russel"],
                 brief="This module provides %RMF I/O",
                 overview=overview,
                 publications=env.IMPStandardPublications(),
                 files=["3O3Y.hdf5.txt", "3O3Y.xml", "simple.hdf5.txt",
                        "simple.xml", "3O3Y.pdb.txt", "simple.pdb.txt",
                        "categories.dox", "rmf.dox", "types.dox"],
                 license=env.IMPStandardLicense())
