Import('env')
import scons_tools.dependency

scons_tools.dependency.add_external_library(env, "HDF5", ["hdf5_cpp", "hdf5"],
                                            "H5Cpp.h",
                                            body='new H5::H5File();',
                                            versionheader="H5version.h",
                                            versioncpp=["H5Acreate_vers"])

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem", 'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p;",
                                               extra_boost_libs=["system"])


env.IMPModuleBuild(version='SVN',
                   required_modules=['kernel', 'atom', 'core', 'algebra', 'container',
                                     'statistics', 'display'],
                   required_dependencies=['HDF5', "Boost.FileSystem"])
