Import('env')

files = ['PairConnectivityRestraint.cpp',
         'ConnectivityRestraint.cpp', 'ProximityRestraint.cpp',
         'RestraintSet.cpp',
         'DistanceRestraint.cpp', 'AngleRestraint.cpp', 'DihedralRestraint.cpp',
         'TorusRestraint.cpp', 'ExclusionVolumeRestraint.cpp',
         'NonbondedRestraint.cpp', 'BondDecoratorRestraint.cpp',
         'SingletonListRestraint.cpp', 'TripletChainRestraint.cpp']

files = [File(x) for x in files]
Return('files')
