Import('env')

env= env.IMPApplication(name="saxs_merge", version='nightly-29/2/2012',
                        authors=["Yannick Spill"],
                        brief="A bayesian SAS merging tool",
                        overview="",
                        license=env.IMPStandardLicense(),
                        publications=[],
                        required_modules=['saxs','isd','gsl'],
                        required_dependencies=[])
if env:
    env.IMPPythonExecutable('saxs_merge.py')
