Import('env')
import scons_tools.paths as stp
# modules must be listed after modules that use them
for s in stp.get_sconscripts(env, ['base',
                                   'benchmark',
                                   'cgal',
                                   'algebra',
                                   'kernel',
                                   'display',
                                   'score_functor',
                                   'core',
                                   'container',
                                   'atom',
                                   'rotamer',
                                   'statistics',
                                   'rmf',
                                   'domino',
                                   'em',
                                   'saxs',
                                   'gsl',
                                   'modeller',
                                   'restrainer',
                                   'multifit',
                                   'cnmultifit',
                                   'em2d',
                                   'misc',
                                   'system',
                                   'isd',
                                   'kmeans',
                                   'parallel',
                                   'pepdock',
                                   # keep at end
                                   'test', 'example']):
    SConscript(s)
