Import('env')

# modules must be listed after modules that use them
cppmodules=['algebra',
            'core',
            'container',
            'atom',
            'display',
            'domino',
            'em',
            'examples',
            'multifit',
            'misc',
            'saxs',
            'helper',
            'statistics',
            'gsl',
            'modeller',
            'benchmark']
pymodules=['restrainer']

for p in cppmodules:
    SConscript(p+"/SConscript")

for p in pymodules:
    SConscript(p+"/SConscript")

if env.get('localmodules', False):
    import os.path

    dirs= Glob("*/SConscript")

    for m in [os.path.split(str(d))[0] for d in dirs]:
        if m not in cppmodules and m not in pymodules:
            SConscript(m+"/SConscript")
