Import('env')

files = ['DistancePairScore.cpp', 'SphereDistancePairScore.cpp',
         'RefineOncePairScore.cpp', 'TypedPairScore.cpp',
         'TransformedDistancePairScore.cpp']

files = [File(x) for x in files]
Return('files')
