Import('env')

files = [
         'Rotation3D.h',
         'Transformation3D.h',
         'Vector3D.h',
         'VectorD.h',
         'geometric_alignment.h',
         'grid_range_D.h',
         'utility.h',
         'MultiArray.h',
         'Matrix2D.h',
         'Matrix3D.h',
         'eigen_analysis.h',
         'Cylinder3D.h',
         'vector_generators.h'
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPHeaders(files)
