Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Ben Webb"],
                 brief="Support for parallel tasks that communicate "
                       "infrequently.",
                 overview="""
This module allows for \\imp tasks to be distributed to multiple processors
or machines. It employs a master-slave model; the main (master) \\imp process
sends the tasks out to one or more slaves. Tasks cannot communicate with each
other, but return results to the master. The master can then start new tasks,
possibly using results returned from completed tasks. The system is fault
tolerant; if a slave fails, any tasks running on that slave are automatically
moved to another slave.

To use the module, first create an IMP::parallel::Manager object. Add one or
more slaves to the Manager using its add_slave method (example slaves are
IMP::parallel::LocalSlave, which simply starts another \\imp process on the
same machine as the master, and IMP::parallel::SGEQsubSlaveArray, which starts
an array of multiple slaves on a Sun GridEngine cluster). Next, call its
get_context method to create a new IMP::parallel::Context object. Add tasks
to the Context with the add_task method (each task is simply a Python function
or other callable object). Finally, call the get_results_unordered method to
send the tasks out to the slaves (a slave only runs a single task at a time;
if there are more tasks than slaves later tasks will be queued until a slave
is done with an earlier task). This method returns the results from each task
as it completes.

Setup in \\imp is often expensive, and thus the Manager::get_context method
allows you to specify a Python function or other callable object to do any
setup for the tasks. This function will be run on the slave before any tasks
from that context are started (the return values from this function are
passed to the task functions). If multiple tasks from the same context are
run on the same slave, the setup function is only called once.
""",
                 publications=env.IMPStandardPublications(),
                 license=env.IMPStandardLicense())
