Import('env')

# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Append(LIBS=env['CGAL_LIBS'])

env.IMPModuleBuild(author='IMP developers', version='SVN',
                   description='General purpose algebraic manipulation.')
