Import('env')
Export('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='General purpose algebraic manipulation.')

env.validate()

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
