Import('env')

env.IMPModuleBuild(version='SVN',
                   required_modules=['kernel'],
                   optional_modules=['cgal'],
                   optional_dependencies=['CGAL', 'ANN'])
