Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost

env.IMPModuleBuild(version='nightly-18/6/2012',
                   required_modules=['kernel', 'atom', 'core', 'algebra', 'container',
                                     'display', "RMF"],
                   required_dependencies=[])
