Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost

env.IMPModuleBuild(version='nightly-22',
                   required_modules=['kernel', 'atom', 'core', 'algebra', 'container',
                                     'statistics', 'display', "RMF"],
                   required_dependencies=[])
