Import('env')

import os.path

dox = env.Doxygen("doxygen.conf")
# Force the population of the build/include/ directory with generated headers
env.Depends(dox, '#/build/include')

docdir = os.path.join(env['docdir'], 'doxygen')

# Install all files from 'dox' directory into the 'docdir' directory (cannot
# use env.InstallAs() right now, due to scons bug #1751)
env.Command(Dir(env.subst(docdir)), dox,
            "install -d $TARGET && install ${SOURCE.dir}/* $TARGET")
