Import('env')

env= env.IMPApplication(name="nmr_rtc", version="SVN",
                        authors=["Dina Schneidman"],
                        brief="Scoring with NMR residue type content term (NMR-RTC)",
                        overview="",
                        license=env.IMPStandardLicense(),
                        publications=['Schneidman-Duhovny D et al. ...'],
                        required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutables([("nmr_rtc_score", ["ResidueContent.cpp",
                                             "nmr_rtc_score.cpp",
                                             "helpers.cpp"]),
                           ("interface_rtc", ["ResidueContent.cpp",
                                              "interface_rtc.cpp",
                                              "helpers.cpp"])])
