Import('env')
import scons_tools.checks

scons_tools.checks.handle_optional_lib(env, "ExampleLib", "example_lib_name",
                                       "example_lib_header.h", extra_libs=[])


# See IMP.gsl for an example of how to add external dependencies to a module
env.IMPModuleBuild(version='SVN',
                   # The required modules are the other IMP modules that must be built to use this one
                   required_modules=['container', 'core'],
                   # the optional dependencies are external libraries that are needed
                   optional_dependencies=["ExampleLib"])
