# Autogenerated file, run tools/build/setup_cmake.py to regenerate

if(NOT DEFINED RMF_LIBRARIES)

set(CHECK_COMPILES_BODY "")

check_compiles("_environment" RMF RMF "#include <RMF/FileHandle.h>" "" "RMF" RMF_ok)
if("${RMF_ok}" MATCHES "1")
message(STATUS "Found RMF in environment")
else()
include(LibFindMacros)

# Use pkg-config to get hints about paths
libfind_pkg_check_modules("RMF_PKGCONF" "rmf")

# Include dir
find_path("RMF_INCLUDE_DIR"
  NAMES RMF/FileHandle.h
  PATHS ${RMF_PKGCONF_INCLUDE_DIRS}
)

# Finally the library itself
foreach(lib RMF)
find_library("${lib}_LIBRARY"
  NAMES ${lib}
  PATHS ${RMF_PKGCONF_LIBRARY_DIRS}
)
set("RMF_LIBRARY" ${RMF_LIBRARY} ${${lib}_LIBRARY})
endforeach(lib)


# Set the include dir variables and the libraries and let libfind_process do the rest.
# NOTE: Singular variables for this library, plural for libraries this this lib depends on.
set(RMF_PROCESS_INCLUDES RMF_INCLUDE_DIR)
set(RMF_PROCESS_LIBS RMF_LIBRARY)
libfind_process(RMF)

if ("${RMF_LIBRARY}" MATCHES ".*NOTFOUND.*"
    OR "${RMF_INCLUDE_DIR}" MATCHES ".*NOTFOUND.*")
  set(RMF_INTERNAL 1 CACHE INTERNAL "" FORCE)
        message(STATUS "Building internal RMF")

set(RMF_BINARY_DIR ${PROJECT_BINARY_DIR}/src/dependency/RMF)

add_subdirectory(${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF ${RMF_BINARY_DIR})

set(RMF_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/include ${RMF_BINARY_DIR}/include  CACHE INTERNAL "" FORCE)
set(RMF_SWIG_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/swig CACHE INTERNAL "" FORCE)
set(RMF_LIBRARIES RMF CACHE INTERNAL "" FORCE)

file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/RMF" "ok=True
includepath=\"${RMF_INCLUDE_PATH}\"
swigpath=\"${RMF_SWIG_PATH}\"
libpath=\"${RMF_SWIG_PATH}\"
")

set(ENV{PYTHONPATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PYTHONPATH})
set(ENV{PATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PATH})

message(STATUS "PATH is now "$ENV{PATH})
message(STATUS "PYTHONPATH is now "$ENV{PYTHONPATH})

file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/RMF" "ok=True")
else()
  check_compiles("_found" "RMF" "RMF" "#include <RMF/FileHandle.h>" "${RMF_INCLUDE_DIR}" "${RMF_LIBRARY}" RMF_ok_ok)
  if(${RMF_ok_ok} MATCHES "1")
    message(STATUS "Found RMF at ""${RMF_INCLUDE_DIR}" " " "${RMF_LIBRARY}")
  else()
    set(RMF_INTERNAL 1 CACHE INTERNAL "" FORCE)
        message(STATUS "Building internal RMF")

set(RMF_BINARY_DIR ${PROJECT_BINARY_DIR}/src/dependency/RMF)

add_subdirectory(${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF ${RMF_BINARY_DIR})

set(RMF_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/include ${RMF_BINARY_DIR}/include  CACHE INTERNAL "" FORCE)
set(RMF_SWIG_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/swig CACHE INTERNAL "" FORCE)
set(RMF_LIBRARIES RMF CACHE INTERNAL "" FORCE)

file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/RMF" "ok=True
includepath=\"${RMF_INCLUDE_PATH}\"
swigpath=\"${RMF_SWIG_PATH}\"
libpath=\"${RMF_SWIG_PATH}\"
")

set(ENV{PYTHONPATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PYTHONPATH})
set(ENV{PATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PATH})

message(STATUS "PATH is now "$ENV{PATH})
message(STATUS "PYTHONPATH is now "$ENV{PYTHONPATH})

file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/RMF" "ok=True")
  endif()
endif()
endif()
else()
message(STATUS "RMF already setup")
if(DEFINED RMF_INTERNAL)
message(STATUS "Building internal RMF")

set(RMF_BINARY_DIR ${PROJECT_BINARY_DIR}/src/dependency/RMF)

add_subdirectory(${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF ${RMF_BINARY_DIR})

set(RMF_INCLUDE_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/include ${RMF_BINARY_DIR}/include  CACHE INTERNAL "" FORCE)
set(RMF_SWIG_PATH ${PROJECT_SOURCE_DIR}/modules/rmf/dependency/RMF/swig CACHE INTERNAL "" FORCE)
set(RMF_LIBRARIES RMF CACHE INTERNAL "" FORCE)

file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/RMF" "ok=True
includepath=\"${RMF_INCLUDE_PATH}\"
swigpath=\"${RMF_SWIG_PATH}\"
libpath=\"${RMF_SWIG_PATH}\"
")

set(ENV{PYTHONPATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PYTHONPATH})
set(ENV{PATH} ${PROJECT_BINARY_DIR}/src/dependency/RMF/:$ENV{PATH})

message(STATUS "PATH is now "$ENV{PATH})
message(STATUS "PYTHONPATH is now "$ENV{PYTHONPATH})

endif(DEFINED RMF_INTERNAL)
endif(NOT DEFINED RMF_LIBRARIES)