Import('env')

env.IMPModuleBuild(version="SVN",
                   required_modules=['core', 'algebra', 'container'],
                   lib_only_required_modules=[],
                   optional_dependencies=['CGAL', 'Boost.FileSystem'])
