Import('env')

env.IMPModuleBuild(version="SVN",
                   required_modules=['core', 'algebra'],
                   lib_only_required_modules=['container'],
                   optional_dependencies=['CGAL', 'Boost.FileSystem'])
