Import('env')

env.IMPModuleBuild(author="Ben Webb, Daniel Russel and Dina Schneidman",
                   version="SVN",
                   description="Code for dealing with protein and atomic structures.",
                   required_modules=['core'],
                   optional_dependencies=['CGAL'])
