Import('env')
files = [
#'learn_fftw.cpp',
         'DataPoints.cpp',
         'DataPointsAssignment.cpp',
         'VQClustering.cpp',
         'density_analysis.cpp',
         'FFTFitting.cpp',
         'weighted_excluded_volume.cpp',
#         'sampling_space.cpp',
         'FittingSolutionRecord.cpp',
#         'SingleDominoRun.cpp',
         'm_rigid_fitting.cpp',
         'fitting_solutions_reader_writer.cpp',
         'fitting_tools.cpp',
         'SettingsData.cpp',
#         'DataContainer.cpp',
#         'restraints_utils.cpp',
#         'sampling_space_utils.cpp',
         'WeightedExcludedVolumeRestraint.cpp',
         'anchor_graph.cpp',
#         'mc_cg_refinement.cpp'
         'RMSDClustering.cpp',
         'fitting_clustering.cpp'
        ]\
# Build and install the shared library:
env.IMPModuleLib(files)
