Import('env')
files = [
         'weighted_excluded_volume.cpp',
         'sampling_space.cpp',
         'FittingSolutionRecord.cpp',
         'SingleDominoRun.cpp',
         'm_rigid_fitting.cpp',
         'fitting_solutions_reader_writer.cpp',
         'fitting_tools.cpp',
         'SettingsData.cpp'
        ]
# Build and install the shared library:
env.IMPModuleLib(env.IMPModuleGetSources())
