Import('env')

env.IMPModuleDoc(files=env.IMPModuleGetDocs(),
                 authors=["Daniel Russel", "Ben Webb"],
                 brief='The \imp kernel provides base classes and key shared functionality.',
                 overview="""The \imp kernel provides the base functionality and abstract
base classes for representation, scoring and sampling. In addition it provides basic functionality
such as I/O, \\ref log "logging" and \\ref assert "Error Reporting"
support as well as tools to help implement functionality.""",
                 publications=env.StandardPublications(),
                 license=env.StandardLicense(),
                 )
