Import('env')

applications=[ 'EMageFit',
                'foxs',
              'integrative_docking',
              'saxs_tools',
              'saxs_merge',
              'em_tools',
              'ligand_score',
              'multifit_tools',
               'rmf_tools',
              'pdb_tools']

if env.get('local', False):
    for d in Glob("*/SConscript"):
        p= str(d).split("/")[0]
        if not p in applications:
            applications.append(p)

for p in applications:
    SConscript(p+"/SConscript")
