Import('env')

applications=['foxs',
              'saxs_tools',
              'em_tools',
              'ligand_score']

if env.get('local', False):
    for d in Glob("*/SConscript"):
        p= str(d).split("/")[0]
        if not p in applications:
            applications.append(p)

for p in applications:
    SConscript(p+"/SConscript")
