Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost


scons_tools.dependency.add_external_library(env, "HDF5", ["hdf5"],
                                            "hdf5.h",
                                            body='H5garbage_collect();')
#                                            versionheader="hdf5.h",
#                                            versioncpp=["H5Acreate_vers"])

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem",
                                               'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p;",
                                               extra_boost_libs=["system"])
scons_tools.dependency.boost.add_boost_library(env, "Thread", "thread",
                                               'boost/thread/mutex.hpp',
                                               body="boost::mutex p;",
                                               extra_boost_libs=["system"])

olinktest=env['linktest']
env['linktest']=False
env.IMPModuleBuild(version='SVN',
                   required_modules=['base'],
                   required_dependencies=['HDF5', "Boost.FileSystem", "Boost.Thread"],
                   module='RMF', module_libname="RMF", module_pylibname="_RMF",
                   module_include_path="RMF",
                   module_preproc="RMF", module_namespace="RMF")
env['linktest']=olinktest
