Import('env')

# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Append(LIBS=env['CGAL_LIBS'])


env.IMPModuleBuild(author='Keren Lasker, Javier Velazquez-Muriel,'
                    'Friedrich Foerster', version='SVN',
                   description='Handling of EM density maps.',
                   required_modules=['atom', 'core', 'algebra'])
