# Autogenerated file, run build/tools/setup_cmake.py to regenerate
execute_process(COMMAND python -c "import modeller"
                RESULT_VARIABLE status)

if (${status})
  message(STATUS "modeller not found")
  file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/modeller" "ok=False")
else()
  message(STATUS "modeller found " ${modeller_INCLUDE_DIR} " " ${modeller_LIBRARY})
  file(WRITE "${PROJECT_BINARY_DIR}/data/build_info/modeller" "ok=True")
endif()