Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Daniel Russel"],
                 brief="MODULENAME provides containers in \imp.",
                 overview="""Containers provide a layer of indirection between code that defines sets of particles and restraints and constraints. This indirection allows the set of particles acted upon to be changed on the fly. For example, the IMP::container::ClosePairContainer defines a set of all particle pairs that are close to one another.""",
                 publications=env.StandardPublications(),
                 license=env.StandardLicense())
