# Include IMP build utility functions:
execfile('SCons.include')

# Set up build environment:

opts = Options('config.py', ARGUMENTS)
add_common_options(opts, "em")

# # Get Modeller and Python locations, and set up a build environment:
env = MyEnvironment(options=opts, tools=["default", "doxygen"],
                    toolpath=["tools"])
Help(opts.GenerateHelpText(env))

Help("""
Type: 'scons' to build the EMBED library;
      'scons test' to run the test cases;
      'scons standards' to check the code against the standards.
""")


# # Make these objects available to SConscript files:
Export('env', 'get_pyext_environment', 'get_sharedlib_environment')

# Check code for coding standards:
standards = env.Command("standards", "SConstruct", "tools/check-standards.py")

bin = SConscript('bin/SConscript')

Export('bin')

src, pyext = SConscript('src/emlib/SConscript')
SConscript('test/SConscript')
SConscript('doc/SConscript')


# bin script first requires libraries to be built:
env.Depends(bin, [src, pyext])

# Build the binaries by default:
env.Default(bin)
