Import('env')

d = env.Publication(authors=["Keren Lasker", "Maya Topf",
                             "Andrej Sali", "Haim J. Wolfson"],
                    title="Inferential optimization for simultaneous fitting "
                          "of multiple components into a cryoEM map of "
                          "their assembly",
                    journal="Journal of Molecular Biology", year="2009")

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Keren Lasker"],
                 brief="MODULENAME contains a protocol for fitting proteins to EM maps.",
                 overview="""MultiFit is a computational method for
simultaneously fitting atomic structures of components into their
assembly density map at resolutions as low as 25A. The
component positions and orientations are optimized with respect to
a scoring function that includes the quality-of-fit of components in the map,
the protrusion of components from the map envelope, as well as the
shape complementarity between pairs of components. The scoring function
is optimized by an exact inference optimizer DOMINO that efficiently
finds the global minimum in a discrete sampling space. For more information please see \\salilab{/MultiFit/,the MultiFit website}.""",
                 publications=env.StandardPublications()+[d],
                 license=env.StandardLicense())
