files = ['DistancePairScore.h', 'SphereDistancePairScore.h',
         'RefineOncePairScore.h', 'TypedPairScore.h',
         'TransformedDistancePairScore.h']

files = [File(f) for f in files]
Return('files')
