Import('env')

# Dunbrack's backbone dependent rotamer library can be obtained from:
# http://dunbrack.fccc.edu/bbdep2010/
#
# files = [
#          'SimpleOpt1-5.2010.ALL.bbdep.rotamers.lib'
#         ]

# Install the data files:
# env.IMPModuleData(files)
env.IMPModuleData(env.IMPModuleGetData())
