Import('env')
import scons_tools.dependency.modeller_test

scons_tools.dependency.modeller_test.configure_check(env)

env.IMPModuleBuild(version='SVN', required_modules=['core'],
                   required_dependencies=['modeller'],
                   python_docs=True)
