Import('env')

# All .dox, .pdf and .pdb files are installed
env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 # A python list of the author names
                 authors=["Daniel Russel"],
                 # Provide a brief description of what the module does
                 brief="This module provides %example showing how to implement various types of objects and functionality in \\imp.",
                 # Provide a longer description of what the module does
                 # This description can have multiple paragraphs and all sorts of markup
                 overview="""The overview section of the module page can contain any doxygen markup as well as references to \\imp classes such as IMP::Model. See \external{http://www.doxygen.org, the doxygen web site} for a full description of what can be done in doxygen.

Remember to escape characters to keep python happy.""",
                 # IMPPublications can be added using the env.IMPPublication() function
                 # The result should be a python list
                 # env.IMPStandardPublications() defines the general IMP publications
                 publications=env.IMPStandardPublications()\
                     + [env.IMPPublication(authors=["Some Person", "Someone Else"],
                                        title="A silly title of no paper",
                                        journal="Dev Null", year=2051),
                        env.IMPWebsite(url="http://www.salilab.org/imp", name="IMP")],
                 # License can be either env.IMPStandardLicense() to be the same as the rest of IMP
                 # or it can be a string describing the license, such as "GPL".
                 license=env.IMPStandardLicense())
