Import('env')

files = [
         'DominoSampler.h',
         'Subset.h',
         'SubsetState.h',
         'domino2_macros.h',
         'particle_states.h',
         'subset_evaluators.h',
         'subset_states.h',
         'utility.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
