# Include IMP build utility functions:
execfile('../SCons.include')

# Get Modeller and Python locations, and set up a build environment:
modconfig = get_modeller_config()
pythoninc = get_python_include(modconfig)
env = MyEnvironment(modconfig, tools=["default", "doxygen"],
                    toolpath=["../tools"])

# Make these objects available to SConscript files:
Export('env', 'modconfig', 'pythoninc', 'configure_for_pyext',
       'is_wine_platform')

# Subdirectories to build:
bin = SConscript('bin/SConscript')
Export('bin')
src, pyext = SConscript('IMP/SConscript')
SConscript('IMP_mov/SConscript')
SConscript('doc/SConscript')

# bin script first require libraries to be built:
env.Depends(bin, [src, pyext])

# Build the binaries by default:
env.Default(bin)
