# Include IMP build utility functions:
import os
import sys
sys.path.append('../')
from tools import *

# Set up build environment:
opts = Options()
add_common_options(opts, "imp")
opts.Add(PackageOption('em', 'Location of the emlib package',
                       os.environ.get('EMINSTALL', False)))
env = MyEnvironment(options=opts, require_modeller=False,
                    tools=["default", "doxygen"],
                    toolpath=["../tools"])
Help(opts.GenerateHelpText(env))

# Make these objects available to SConscript files:
Export('env', 'get_pyext_environment', 'get_sharedlib_environment',
       'invalidate_environment')

# Subdirectories to build:
bin = SConscript('bin/SConscript')
Export('bin')
src = SConscript('src/SConscript')
pyext = SConscript('pyext/SConscript')
SConscript('test/SConscript')
SConscript('rsr/IMP_mov/SConscript')
SConscript('doc/SConscript')
SConscript('impEM/SConscript')

# bin script first requires libraries to be built:
env.Depends(bin, [src, pyext])

# Build the binaries by default:
env.Default(bin)
