# Include IMP build utility functions:
execfile('../SCons.include')

# Get Modeller and Python locations, and set up a build environment:
modconfig = get_modeller_config()
pythoninc = get_python_include(modconfig)
env = MyEnvironment(modconfig)

# Make these objects available to SConscript files:
Export('env', 'modconfig', 'pythoninc', 'configure_for_pyext',
       'is_wine_platform')

# Subdirectories to build:
src = SConscript('IMP/SConscript')
SConscript('IMP_mov/SConscript')

# Build the library (src directory) and Python extension by default:
env.Default(src)
