/**
 *  \file TripletModifier.cpp   \brief A function on Particles.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2011 IMP Inventors. All rights reserved.
 *
 */

#include "IMP/TripletDerivativeModifier.h"
#include "IMP/internal/utility.h"

IMP_BEGIN_NAMESPACE

TripletDerivativeModifier::TripletDerivativeModifier(std::string name):
  Object(name){
}

IMP_END_NAMESPACE
