Import('env')

env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  spelling_exceptions=['xplor', 'yorigin', 'timessig', 'yz',
                       'rnormfac', 'rsigsq', 'kdist', 'vsigsq', 'normfac',
                       'nx', 'rsig', 'nz', 'xy', 'params', 'sigsq', 'xorigin',
                       'rkdist', 'vsig', 'xz', 'zorigin'],
                  # CoarseCC and CoarseConvolution contain only static methods
                  value_object_exceptions=['DensityHeader', 'CoarseCC',
                                           'CoarseConvolution', 'floats'],
                  show_exceptions=['CoarseCC', 'CoarseConvolution', 'floats'])
