/**
 *  \file QuadPredicate.h    \brief Define QuadPredicate.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2011 IMP Inventors. All rights reserved.
 */

#ifndef IMPKERNEL_QUAD_PREDICATE_H
#define IMPKERNEL_QUAD_PREDICATE_H

#include "kernel_config.h"
#include "base_types.h"
#include "ParticleTuple.h"
#include "DerivativeAccumulator.h"
#include "internal/container_helpers.h"

IMP_BEGIN_NAMESPACE

//! Abstract predicate function
/** A predicate is a function which returns one of a discrete set of
    values (eg -1, 0, 1 depending on whether a value is negative, zero
    or positive). QuadPredicates will evaluate the predicate for the passed
    particles.

    Implementers should check out IMP_QUAD_PREDICATE().
*/
class IMPEXPORT QuadPredicate : public base::Object
{
 public:
  typedef ParticleQuad Argument;
  QuadPredicate(std::string name="QuadPredicate %1%");
  //! Compute the predicate.
  virtual int get_value(const ParticleQuad& vt) const =0;

  /** Implementations
      for these are provided by the IMP_QUAD_PREDICATE()
      macro.
  */
  virtual Ints get_value(const ParticleQuadsTemp &o) const {
    Ints ret(o.size());
    for (unsigned int i=0; i< o.size(); ++i) {
      ret[i]+= get_value(o[i]);
    }
    return ret;
  }



  //! Compute the predicate and the derivative if needed.
  virtual int get_value_index(Model *m, const ParticleIndexQuad& vt) const {
    return get_value(internal::get_particle(m, vt));
  }

  /** Implementations
      for these are provided by the IMP_QUAD_PREDICATE()
      macro.
  */
  virtual Ints get_value_index(Model *m,
                                const ParticleIndexQuads &o) const {
    Ints ret(o.size());
    for (unsigned int i=0; i< o.size(); ++i) {
      ret[i]+= get_value_index(m, o[i]);
    }
    return ret;
  }



  /** Get the set of particles read when applied to the arguments. */
  virtual ParticlesTemp
    get_input_particles(Particle *p) const =0;

  /** Get the set of input containers when this modifier is applied to
      the arguments. */
  virtual ContainersTemp
    get_input_containers(Particle *p) const =0;

  IMP_REF_COUNTED_DESTRUCTOR(QuadPredicate);
};

IMP_OBJECTS(QuadPredicate,QuadPredicates);



IMP_END_NAMESPACE

#endif  /* IMPKERNEL_QUAD_PREDICATE_H */
