Import('env')

env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  expensive_python_tests= env.IMPModuleGetExpensivePythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  value_object_exceptions=['HierarchyVisitor', 'ModifierVisitor'],
                  function_name_exceptions=['RigidBody.normalize_rotation','transform'],
                  show_exceptions=['HierarchyVisitor', 'ModifierVisitor'])
