import os.path
Import('env')

files = ['base_types.h', 'Index.h', 'Model.h',
         'Particle.h', 'ScoreState.h', 'OptimizerState.h', 'IMP_config.h',
         'ModelData.h', 'RigidBody.h', 'log.h', 'DerivativeAccumulator.h',
         'Key.h', 'AttributeTable.h', 'utility.h', 'Restraint.h', 'Optimizer.h',
         'DecoratorBase.h', 'Object.h', 'Vector3D.h', 'ScoreFuncParams.h',
         'UnaryFunction.h', 'PairScore.h', 'SingletonScore.h', 'macros.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP')
inst = env.Install(includedir, files)
env.Alias('install', inst)

# Subdirectories
SConscript('restraints/SConscript')
SConscript('optimizers/SConscript')
SConscript('decorators/SConscript')
SConscript('unary_functions/SConscript')
SConscript('pair_scores/SConscript')
SConscript('singleton_scores/SConscript')
SConscript('score_states/SConscript')
