Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=['Daniel Russel', 'Ben Webb', 'Dina Schneidman',
                          'Javier Vel&aacute;zquez-Muriel'],
                 brief='This module contains functionality for dealing with atoms and proteins.',
                 overview="""This module provides a variety of functionality for loading, creating, manipulating and scoring atomic structures. Molecules and collections of molecules are represented using Hierarchy particles. Whenever possible, one should prefer to use IMP::atom::Selection and related helper functions to manipulate molecules as that provides a simple and biologically relevant way of describing parts of molecules of interest.

                 \section conventions Conventions
                 The name "residue index" is used to refer to the index of the residue in the conventional description of the protein, as opposed to its index among the set of residues which are found in the current molecule. The same concept is know as the "residue number" in pdb files. This index is not necessarily unique within a Chain, however, the combination of the residue index and insertion code should be.

                 """,
                 publications=env.IMPStandardPublications(),
                 license=env.IMPStandardLicense())
