Import('env')

files = [
         'Key.h',
         'KeyCategory.h',
         'NodeHandle.h',
         'NodeID.h',
         'RootHandle.h',
         'atom_io.h',
         'geometry_io.h',
         'hdf5_types.h',
         'hdf5_wrapper.h',
         'names.h',
         'operations.h',
         'particle_io.h',
         'restraint_io.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
