Import('env')

files = [
         'Atom.cpp',
         'BondEndpointsRefiner.cpp',
         'BondPairContainer.cpp',
         'BondSingletonScore.cpp',
         'BondedPairFilter.cpp',
         'BrownianDynamics.cpp',
         'Chain.cpp',
         'Charged.cpp',
         'CharmmParameters.cpp',
         'CoulombPairScore.cpp',
         'CoverBond.cpp',
         'Diffusion.cpp',
         'Domain.cpp',
         'ForceFieldParameters.cpp',
         'Fragment.cpp',
         'Hierarchy.cpp',
         'LennardJones.cpp',
         'LennardJonesPairScore.cpp',
         'Mass.cpp',
         'MolecularDynamics.cpp',
         'Residue.cpp',
         'SimulationParameters.cpp',
         'VelocityScalingOptimizerState.cpp',
         'bond_decorators.cpp',
         'bond_graph.cpp',
         'distance.cpp',
         'element.cpp',
         'estimates.cpp',
         'force_fields.cpp',
         'hierarchy_tools.cpp',
         'mol2.cpp',
         'pdb.cpp',
         'smoothing_functions.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
env.IMPModuleLib(files)
