Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'Atom.cpp',
         'BondEndpointsRefiner.cpp',
         'BondPairContainer.cpp',
         'BondSingletonScore.cpp',
         'BrownianDynamics.cpp',
         'Chain.cpp',
         'Diffusion.cpp',
         'Domain.cpp',
         'MolecularDynamics.cpp',
         'MolecularHierarchy.cpp',
         'Residue.cpp',
         'VelocityScalingOptimizerState.cpp',
         'bond_decorators.cpp',
         'bond_graph.cpp',
         'estimates.cpp',
         'pdb.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
