Import('env')

files = [
         'atom_hierarchy.h',
         'optimization.h',
         'simplify_atom_hierarchy.h',
         'simplify_restraint.h',
        ]

# Install the include files:
env.IMPModuleInclude(files)
