Import("env")

files = [
    "opencv_interface.h",
    "align2D.h" ,
    "filenames_manipulation.h" ,
    "FFTinterface.h" ,
    "FFToperations.h" ,
    "Fine2DRegistrationRestraint.h" ,
    "image_processing.h" ,
    "labeling_algorithm.h" ,
    "model_interaction.h" ,
    "pca_features_extraction.h" ,
    "project.h" ,
    "ProjectionFinder.h" ,
    "Pixel.h" ,
    "ProjectionMask.h" ,
    "CenteredMat.h" ,
    "ProjectionParameters.h" ,
    "PolarResamplingParameters.h",
    "RegistrationResult.h" ,
    "scores2D.h",
    "Em2DRestraint.h",
    "Image.h",
    "SpiderImageReaderWriter.h",
    "JPGImageReaderWriter.h",
    "ImageReaderWriter.h",
      ] + SConscript("internal/SConscript")

# Install the include files:
env.IMPModuleInclude(files)
