Import("env")

files = [
    "opencv_interface.h",
    "align2D.h" ,
    "filenames_manipulation.h" ,
    "FFToperations.h" ,
    "Fine2DRegistrationRestraint.h" ,
    "image_processing.h" ,
    "model_interaction.h" ,
    "pca_features_extraction.h" ,
    "project.h" ,
    "ProjectionFinder.h" ,
    "ProjectionMask.h" ,
    "CenteredMat.h" ,
    "ProjectionParameters.h" ,
    "PolarResamplingParameters.h",
    "RegistrationResult.h" ,
    "scores2D.h",
    "Em2DRestraint.h",
    "Image.h",
    "SpiderImageReaderWriter.h",
    "JPGImageReaderWriter.h",
    "TIFFImageReaderWriter.h",
    "ImageReaderWriter.h",
    "hierarchical_clustering.h",
    "CollisionCrossSection.h",
    "domino_particle_states.h",
    "domino_filters.h",
    "domino_filter_tables.h",
#    "TemplateFinder.h",
   "RigidBodiesImageFitRestraint.h",

      ] + SConscript("internal/SConscript")

# Install the include files:
env.IMPModuleInclude(files)
