/**
 *  \file ListQuadContainer.h    \brief Store a list of ParticleQuadsTemp
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 IMP Inventors. All rights reserved.
 */

#ifndef IMPCORE_INTERNAL_CORE_LIST_QUAD_CONTAINER_H
#define IMPCORE_INTERNAL_CORE_LIST_QUAD_CONTAINER_H

#include "../core_config.h"
#include <IMP/QuadContainer.h>
#include <IMP/internal/container_helpers.h>
#include "quad_helpers.h"
#include <IMP/ScoreState.h>

IMPCORE_BEGIN_INTERNAL_NAMESPACE


class IMPCOREEXPORT CoreListQuadContainer:
public internal::ListLikeQuadContainer
{
  IMP_ACTIVE_CONTAINER_DECL(CoreListQuadContainer);
public:
  CoreListQuadContainer(Model *m, std::string name);
  CoreListQuadContainer(Model *m, const char *name);
  CoreListQuadContainer();
  void add_particle_quad(const ParticleQuad& vt);
  void add_particle_quads(const ParticleQuadsTemp &c);
  void remove_particle_quads(const ParticleQuadsTemp &c);
  void set_particle_quads(ParticleQuadsTemp c);
  void clear_particle_quads();
#ifndef IMP_DOXYGEN
  bool get_is_up_to_date() const {
    return true;
  }
  bool get_contained_particles_changed() const;
  ParticlesTemp get_contained_particles() const;
#endif
  IMP_LISTLIKE_QUAD_CONTAINER(CoreListQuadContainer);
};


IMPCORE_END_INTERNAL_NAMESPACE

#endif  /* IMPCORE_INTERNAL_CORE_LIST_QUAD_CONTAINER_H */
