files = [
         'ArrayOnAttributesHelper.h',
         'DifferenceSingletonContainer.h',
         'Grid3D.h',
         'MinimalSet.h',
         'MovedSingletonContainer.h',
         'ParticleGrid.h',
         'bond_helpers.h',
         'close_pairs_helpers.h',
         'evaluate_distance_pair_score.h',
         'graph_base.h',
         'hierarchy_helpers.h',
         'pair_helpers.h',
         'quad_helpers.h',
         'remove_pointers.h',
         'rigid_bodies.h',
         'rigid_body_tree.h',
         'singleton_helpers.h',
         'triplet_helpers.h',
         'truncated_harmonic.h',
        ]

files = [File(x) for x in files]
Return('files')
