import os.path
Import('env')

files = ['ConnectivityRestraint.h', 'ProximityRestraint.h',
         'SphericalRestraint.h', 'DistanceRestraint.h', 'AngleRestraint.h',
         'DihedralRestraint.h', 'RestraintSet.h', 'ExclusionVolumeRestraint.h',
         'TorusRestraint.h', 'PairConnectivityRestraint.h',
         'NonbondedRestraint.h', 'BondDecoratorRestraint.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'restraints')
inst = env.Install(includedir, files)
env.Alias('install', inst)
