import os.path
Import('env')

files = ['ConnectivityRestraint.h',
         'DistanceRestraint.h', 'AngleRestraint.h',
         'DihedralRestraint.h', 'RestraintSet.h',
         'NonbondedRestraint.h', 'BondDecoratorRestraint.h',
         'SingletonListRestraint.h', 'PairListRestraint.h',
         'TripletChainRestraint.h', 'PairChainRestraint.h',
         'ConstantRestraint.h', 'TunnelRestraint.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'restraints')
inst = env.Install(includedir, files)
env.Alias('install', inst)
