files = ['ConnectivityRestraint.h',
         'DistanceRestraint.h', 'AngleRestraint.h',
         'DihedralRestraint.h', 'RestraintSet.h',
         'NonbondedRestraint.h', 'BondDecoratorRestraint.h',
         'SingletonListRestraint.h', 'PairListRestraint.h',
         'TripletChainRestraint.h', 'PairChainRestraint.h',
         'ConstantRestraint.h']

files = [File(f) for f in files]
Return('files')
