/**
 *  \file CLASSNAMEContainer.cpp   \brief Container for LCCLASSNAME.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 *
 */

#include "IMP/CLASSNAMEContainer.h"
#include "IMP/internal/utility.h"
#include "IMP/internal/InternalListCLASSNAMEContainer.h"
#include "IMP/CLASSNAMEModifier.h"

IMP_BEGIN_NAMESPACE


CLASSNAMEContainer::CLASSNAMEContainer(Model *m, std::string name):
  Container(m,name){
}

// here for gcc
CLASSNAMEContainer::~CLASSNAMEContainer(){
}
/*
CLASSNAMEContainerInput::CLASSNAMEContainerInput(const PLURALVARIABLETYPE &in) {
  Model *m=internal::get_model(in.begin(),
                               in.end());
  IMP_NEW(internal::CoreListCLASSNAMEContainer, c,
          (m, "temporary container"));
  c->set_FUNCTIONNAMEs(in);
  P::operator=(c);
  }*/

IMP_END_NAMESPACE
