Import('env')
env= env.IMPApplication(required_modules=['atom', 'container'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)
if env:
    env.IMPCPPExecutable(target="example", source=["example.cpp"])
