import os.path
Import('env')

files = ['BondDecoratorListScoreState.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'score_states',
                          'bonded_lists')
inst = env.Install(includedir, files)
env.Alias('install', inst)
