import os.path
Import('env')

files = ['Harmonic.h', 'HarmonicLowerBound.h', 'HarmonicUpperBound.h',
         'OpenCubicSpline.h', 'ClosedCubicSpline.h', 'Cosine.h', 'Linear.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'unary_functions')
inst = env.Install(includedir, files)
env.Alias('install', inst)
