#!/usr/bin/python
import sys
import os

def filter(name, value, scorename, args, fromargs, infile):
    cname= name.title().replace(' ', '')
    ucname= name.upper().replace(' ', '_') 
    lcname= name.lower().replace(' ', '_')
    return infile.replace("CLASSNAME", ucname)\
        .replace("FromClassnameArguments", fromargs)\
        .replace("ClassnameArguments", args)\
        .replace("Classname", cname) \
        .replace("classname", lcname) \
        .replace("Value", value) \
        .replace("Groupname", scorename) \
        .replace("GROUPNAME", scorename.upper()) \
        .replace("groupname", scorename.lower())


def make_one(name, value, multi, args, fromargs):
    path= os.getcwd()+"/"
    cname= name.title().replace(' ', '')
    lcvalue= value.lower().replace(' ', '_').replace('*','')
    lcname= multi.lower().replace(' ', '_')

    print "Creating class "+cname + "Container"
    
  

    for p in (("kernel/include/"+multi + "Container.h",
               path+"modules/core/tools/container_templates/container.hpp"),
              ("kernel/src/"+multi + "Container.cpp",
               path+"/modules/core/tools/container_templates/container.cc"),
              ("modules/core/include/List"+multi + "Container.h",
               path+"/modules/core/tools/container_templates/list.hpp"),
              ("modules/core/src/List"+multi + "Container.cpp",
               path+"/modules/core/tools/container_templates/list.cc"),
              ("modules/core/include/"+multi + "sRestraint.h",
               path+"/modules/core/tools/container_templates/restraint.hpp"),
              ("modules/core/src/"+multi + "sRestraint.cpp",
               path+"/modules/core/tools/container_templates/restraint.cc"),

              ("modules/core/include/"+multi + "Restraint.h",
               path+"/modules/core/tools/container_templates/srestraint.hpp"),
              ("modules/core/src/"+multi + "Restraint.cpp",
               path+"/modules/core/tools/container_templates/srestraint.cc"),

              ("modules/core/include/FilteredList"+multi + "Container.h",
               path+"/modules/core/tools/container_templates/filter.hpp"),
              ("modules/core/src/FilteredList"+multi + "Container.cpp",
               path+"/modules/core/tools/container_templates/filter.cc"),
              ("modules/core/include/"+multi + "ContainerSet.h",
               path+"/modules/core/tools/container_templates/set.hpp"),
              ("modules/core/src/"+multi + "ContainerSet.cpp",
               path+"/modules/core/tools/container_templates/set.cc"),
              ("modules/core/include/"+multi + "sScoreState.h",
               path+"/modules/core/tools/container_templates/state.hpp"),
              ("modules/core/src/"+multi + "sScoreState.cpp",
               path+"/modules/core/tools/container_templates/state.cc"),
  
              ("modules/core/include/"+multi + "ScoreState.h",
               path+"/modules/core/tools/container_templates/sstate.hpp"),
              ("modules/core/src/"+multi + "ScoreState.cpp",
               path+"/modules/core/tools/container_templates/sstate.cc"),
  
              ("kernel/include/"+multi + "Modifier.h",
               path+"/modules/core/tools/container_templates/function.hpp"),
              ("kernel/src/"+multi + "Modifier.cpp",
               path+"/modules/core/tools/container_templates/function.cc"),
              ("modules/core/include/Minimum"+multi + "ScoreRestraint.h",
               path+"/modules/core/tools/container_templates/min.hpp"),
              ("modules/core/src/Minimum"+multi + "ScoreRestraint.cpp",
               path+"/modules/core/tools/container_templates/min.cc"),
              ("modules/core/include/Maximum"+multi + "ScoreRestraint.h",
               path+"/modules/core/tools/container_templates/max.hpp"),
              ("modules/core/src/Maximum"+multi + "ScoreRestraint.cpp",
               path+"/modules/core/tools/container_templates/max.cc"),
              ("modules/core/test/containers/test_"+cname + "_restraint.py",
               path+"/modules/core/tools/container_templates/test.py"),
              ("modules/core/pyext/"+lcname+"_containers.i",
               path+"/modules/core/tools/container_templates/swig.i"),
              ("modules/core/test/containers/test_"+cname + "_state.py",
               path+"/modules/core/tools/container_templates/test_state.py"),
              ):
        ofile= open(p[0], 'w')
        ifile= open(p[1], 'r')
        contents= ifile.read()
        print "writing " + p[0]
        ofile.write(filter(name, value, multi, args, fromargs, contents))

def main():
    make_one("particle", "Particle*", "Singleton", "Particle *a", "a")
    make_one("particle pair", "ParticlePair", "Pair", "Particle *a, Particle *b",
             "ParticlePair(a,b)")
    #make_one("particle triplet", "ParticleTriplet", "Triplet", "Particle *a, Particle *b, Particle *c")

  


if __name__ == '__main__':
    main()
