Import('env')

# Subdirectories:
src = SConscript('src/SConscript')
SConscript('doc/SConscript')
SConscript('include/SConscript')
if env.get('python', True):
    (pyext, pymod, pyfiles)=SConscript('pyext/SConscript')
    test = SConscript('test/SConscript')
    env.Depends(test, pyext)
else:
    print "Testing disable since there is no python support"

Return('src')
