Import('env')

# Subdirectories:
src = SConscript('src/SConscript')
SConscript('doc/SConscript')
SConscript('include/SConscript')
pyext = SConscript('pyext/SConscript')
test = SConscript('test/SConscript')
env.Depends(test, pyext)

Return('src', 'pyext')
