Import('env')

env= env.IMPApplication(name="foxsdock", version="SVN",
                        authors=["Dina Schneidman"],
                        brief="Scoring with SAXS term (part of FoXSDock protocol)",
                        overview="",
                        license=env.IMPStandardLicense(),
                        publications=['Schneidman-Duhovny D, Hammel M, Sali A. Macromolecular docking restrained by a small angle X-ray scattering profile. J Struct Biol. 2010'],
                        required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="saxs_score", source=["saxs_score.cpp", "helpers.cpp"])
