/**
 *  \file DynamicListTripletContainer.cpp
 *  \brief A list of ParticleTripletsTemp.
 *
 *  This file is generated by a script (internal/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 *
 */

#include "IMP/internal/InternalDynamicListTripletContainer.h"
#include "IMP/TripletModifier.h"
#include <IMP/base/check_macros.h>
#include <IMP/compatibility/set.h>
#include <algorithm>


IMP_BEGIN_INTERNAL_NAMESPACE

InternalDynamicListTripletContainer
::InternalDynamicListTripletContainer(Container *m,
                                        std::string name):
    P(m->get_model(), name), scope_(m) {
}


InternalDynamicListTripletContainer
::InternalDynamicListTripletContainer(Container *m,
                                        const char *name):
    P(m->get_model(), name), scope_(m) {
}


void InternalDynamicListTripletContainer::do_show(std::ostream &out) const {
  IMP_CHECK_OBJECT(this);
  out << get_access()
      << " Triplets." << std::endl;
}
void InternalDynamicListTripletContainer::add(const ParticleIndexTriplet& vt) {
  ParticleIndexTriplets cur;
  swap(cur);
  cur.push_back(vt);
  swap(cur);
}
void InternalDynamicListTripletContainer
::add(const ParticleIndexTriplets &c) {
  if (c.empty()) return;
  ParticleIndexTriplets cur;
  swap(cur);
  cur+=c;
  swap(cur);
}

void InternalDynamicListTripletContainer::set(ParticleIndexTriplets cp) {
  swap(cp);
}
void InternalDynamicListTripletContainer::clear() {
  ParticleIndexTriplets t;
  swap(t);
}
bool InternalDynamicListTripletContainer::
check_list(const ParticleIndexes& cp) const {
  ParticleIndexes app
    = IMP::internal::get_index(scope_->get_all_possible_particles());

  compatibility::set<ParticleIndex> all(app.begin(),
                                    app.end());
  for (unsigned int i=0; i< cp.size(); ++i) {
    IMP_USAGE_CHECK(all.find(cp[i]) != all.end(),
                    "Particle " << cp[i]
                    << " is not in the list of all possible particles");
  }
  return true;
}

ParticlesTemp
InternalDynamicListTripletContainer::get_all_possible_particles() const {
  return scope_->get_all_possible_particles();
}

void InternalDynamicListTripletContainer::do_before_evaluate() {
}


ParticlesTemp
InternalDynamicListTripletContainer::get_input_particles() const {
  return ParticlesTemp();
}

ContainersTemp
InternalDynamicListTripletContainer::get_input_containers() const {
  return ContainersTemp();
}


ParticleIndexTriplets
InternalDynamicListTripletContainer::get_all_possible_indexes() const {
  return get_indexes();
}


IMP_END_INTERNAL_NAMESPACE
