Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost
import scons_tools.dependency.gcc

deplist=[]

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem",
                                               'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p;",
                                               extra_boost_libs=["system"])
deplist.append('Boost.FileSystem')

config=[]

env.IMPModuleBuild(lib_only_required_modules=['compatibility'],
                   required_dependencies=deplist,
                   config_macros=config)
