Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost
import scons_tools.dependency.gcc

deplist=[]

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem",
                                               'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p;",
                                               extra_boost_libs=["system"])
scons_tools.dependency.add_external_library(env, "gflags",
                                            ["gflags"],
                                            body="google::SetVersionString(\"nope\");",
                                            header="gflags/gflags.h",
    build_script="dependency/install_gflags.sh")
scons_tools.dependency.add_external_library(env, "GPerfTools",
                                            ["profiler"],
                                            "gperftools/profiler.h",
                                            body='ProfilerStop();')

scons_tools.dependency.add_external_library(env, "tcmalloc_heapchecker",
                                            ["tcmalloc"],
                                            header="gperftools/heap-checker.h",
                                            body="new HeapLeakChecker(\"profiler\");",
    enabled=False)

scons_tools.dependency.add_external_library(env, "tcmalloc_heapprofiler",
                                            ["tcmalloc"],
                                            header="gperftools/heap-profiler.h",
                                            body="HeapProfilerStart(\"profiler\");",
    enabled=False)

env.IMPModuleBuild()
