import os
import os.path

Import('env')
penv = env.Clone()
penv.Prepend(CPPPATH=['#/build/include'])
penv.Prepend(LIBPATH=['#/build/lib'])
penv.Prepend(LIBS=['imp_atom', 'imp_core', 'imp_algebra', 'imp'])
if env['build']=='profile' and env['CC'] == 'gcc':
    penv.Prepend(LINKFLAGS=['-static'])

fs = Glob("*.cpp")

all=[]
for f in fs:
    prog= penv.Program(f.rstr())
    all.append(prog)

Return('all')
