import os
import os.path

Import('env')
env= env.IMPApplication(name="rmf_tools", version='nightly-2/3/2012',
                        authors=["Daniel Russel"],
                        brief="An example set of applications.",
                        overview="An example application.""",
                        license=env.IMPStandardLicense(),
                        publications=[],
                        required_modules=['atom', 'container'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)
if env:
    fs = Glob("*.cpp")
    for f in fs:
        src= f
        targetname=f.path.replace(".cpp", "")
        prog= env.IMPCPPExecutable(source=[src], target=targetname)
