set(sources ${sources}
${PROJECT_SOURCE_DIR}/src/CoordinateTransformer.cpp
${PROJECT_SOURCE_DIR}/src/FileConstHandle.cpp
${PROJECT_SOURCE_DIR}/src/FileHandle.cpp
${PROJECT_SOURCE_DIR}/src/FrameConstHandle.cpp
${PROJECT_SOURCE_DIR}/src/FrameHandle.cpp
${PROJECT_SOURCE_DIR}/src/FrameID.cpp
${PROJECT_SOURCE_DIR}/src/Key.cpp
${PROJECT_SOURCE_DIR}/src/NodeConstHandle.cpp
${PROJECT_SOURCE_DIR}/src/NodeHandle.cpp
${PROJECT_SOURCE_DIR}/src/NodeID.cpp
${PROJECT_SOURCE_DIR}/src/SetCurrentFrame.cpp
${PROJECT_SOURCE_DIR}/src/Validator.cpp
${PROJECT_SOURCE_DIR}/src/config.cpp
${PROJECT_SOURCE_DIR}/src/decorator_utility.cpp
${PROJECT_SOURCE_DIR}/src/decorators.cpp
${PROJECT_SOURCE_DIR}/src/exceptions.cpp
${PROJECT_SOURCE_DIR}/src/hdf5_wrapper.cpp
${PROJECT_SOURCE_DIR}/src/log.cpp
${PROJECT_SOURCE_DIR}/src/names.cpp
${PROJECT_SOURCE_DIR}/src/utility.cpp
)
