Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'Rotation3D.cpp',
         'Transformation3D.cpp',
         'geometric_alignment.cpp',
         'eigen_analysis.cpp'
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
