Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'Cone3D.cpp',
         'Cylinder3D.cpp',
         'Plane3D.cpp',
         'Rotation3D.cpp',
         'Segment3D.cpp',
         'Sphere3D.cpp',
         'Sphere3DPatch.cpp',
         'SphericalVector3D.cpp',
         'Transformation2D.cpp',
         'Transformation3D.cpp',
         'eigen_analysis.cpp',
         'endian.cpp',
         'geometric_alignment.cpp',
         'interpolation.cpp',
         'io.cpp',
         'vector_generators.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
