repository="../svn"
includepath="path_to_imp_build/include"
libpath="path_to_imp_build/lib"
path="path_to_imp_build/bin"
swigpath="path_to_imp_build/swig"
datapath="path_to_imp_build/data"
build="debug"
