import os.path
Import('env')

files = ['base_types.h', 'Index.h', 'ScoreFunc.h', 'Model.h',
         'Particle.h', 'State.h', 'IMP_config.h', 'ModelData.h', 'RigidBody.h',
         'log.h', 'DerivativeAccumulator.h', 'Key.h', 'AttributeTable.h',
         'utility.h', 'Restraint.h', 'Optimizer.h', 'DecoratorBase.h',
         'Object.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP')
inst = env.Install(includedir, files)
env.Alias('install', inst)

# Subdirectories
SConscript('restraints/SConscript')
SConscript('optimizers/SConscript')
SConscript('decorators/SConscript')
