Import('env')

env= env.IMPSystem(name="Groel",
                   authors=["Keren Lasker"],
                   brief="Compute the scattering profile of an assembly",
                   overview="",
                   license=env.IMPStandardLicense(),
                   publications=[],
                   required_modules=['em'])
