Import('env')

env= env.IMPSystem(name="Groel", version="SVN",
                   authors=["Keren Lasker"],
                   brief="Solve the structure of Groel using some data.",
                   overview="The structures have been computed from various data. The resulting structure has a XX nm resolution.",
                   license=env.IMPStandardLicense(),
                   publications=[],
                   required_modules=['em'])
