import os.path
Import('env')

files = ['HierarchyDecorator.h', 'NameDecorator.h', 'utility.h', 'graph_base.h',
         'XYZDecorator.h', 'ResidueDecorator.h', 'AtomDecorator.h',
         'MolecularHierarchyDecorator.h', 'bond_decorators.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'decorators')
inst = env.Install(includedir, files)
env.Alias('install', inst)
