Import('env')
e = env.IMPSharedLibraryEnvironment()

files = ['converters.cpp',
         'FitRestraint.cpp',
         'IMPParticlesAccessPoint.cpp',
         'SpiderReaderWriter.cpp',
         'ImageHeader.cpp',
         'header_converters.cpp',
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
