Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'EMFitRestraint.cpp',
         'IMPParticlesAccessPoint.cpp',
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
