Import('env')

files = ('BondCoverParticleRefiner.h', 'RefineOncePairScore.h',
         'ChildrenParticleRefiner.h', 'TunnelSingletonScore.h',
         'CoverBondsScoreState.h', 'WormLikeChain.h')

# Install the include files:
env.IMPHeaders(files)
