Import('env')

files = [
         'BondCoverParticleRefiner.h',
         'ChildrenParticleRefiner.h',
         'CoverBondsScoreState.h',
         'LowestRefinedPairScore.h',
         'RefineOncePairScore.h',
         'TunnelSingletonScore.h',
         'WormLikeChain.h',
        ]

# Install the include files:
env.IMPHeaders(files)
