import os.path
Import('env')

files = ['BondedListScoreState.h', 'NonbondedListScoreState.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'score_states')
inst = env.Install(includedir, files)
env.Alias('install', inst)
