import os.path
Import('env')

files = ['ConnectivityRestraint.h', 'ProximityRestraint.h',
         'SphericalRestraint.h', 'DistanceRestraint.h', 'AngleRestraint.h',
         'RestraintSet.h', 'ExclusionVolumeRestraint.h', 'TorusRestraint.h',
         'PairConnectivityRestraint.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'restraints')
inst = env.Install(includedir, files)
env.Alias('install', inst)
