files = [
         'CombState.h',
         'DiscreteSampler.h',
         'DominoOptimizer.h',
         'JEdge.h',
         'JNode.h',
         'JunctionTree.h',
         'RestraintEvaluator.h',
         'RestraintGraph.h',
        ]

files = [File(x) for x in files]
Return('files')
