Import('env')

# Don't complain that the unittest classes don't conform to IMP standards


# This finds all python files matching test_*.py and all cpp files
# matching test_*.cpp
env.IMPModuleTest()
