Import('env')

files = [
         'top.lib',
         'top_heav.lib',
         'par.lib',
         'radii.lib',
         'protein_ligand_pose_score.lib',
         'protein_ligand_rank_score.lib',
         'dope_score.lib',
         'dope_scorehr.lib'
        ]

# Install the data files:
env.IMPModuleData(files)
