Import('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='Code to write to graphics formats.')

env.Append(LIBS=['imp_core', 'imp_algebra', 'imp_atom'])
env.validate()

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
SConscript('bin/SConscript', exports='env')
