Import('env')
Export('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='Code to write to graphics formats.')

env.Append(LIBS=['imp_core', 'imp_algebra', 'imp_atom'])
env.validate()

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
SConscript('bin/SConscript')
