import os.path

Import('env')

# Python files
files = ['modeller.py', 'test.py', 'pdb.py', 'utils.py']

# Install in lib directory:
pymod = env.Install('#/build/libs/IMP/', files)

pydir = os.path.join(env['pythondir'], 'IMP')
pyinst = env.Install(pydir, files)
env.Alias('install', pyinst)

Return('pymod')
