Import('env')

# Python files
files = ['test.py']

# Install in lib directory:
pymod = env.LinkInstall('#/build/lib/IMP/', files)

pydir = env.GetInstallDirectory('pythondir', 'IMP')
pyinst = env.Install(pydir, files)
env.Alias('install', pyinst)
env.Alias('kernel-install', pyinst)

Return('pymod')
