/**
 *  \file ListGroupnameContainer.cpp   \brief A list of Classnames.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/ListGroupnameContainer.h"
#include <algorithm>


IMPCORE_BEGIN_NAMESPACE

ListGroupnameContainer::ListGroupnameContainer(const Classnames &ps){
  sorted_=false;
  set_classnames(ps);
  set_is_editing(false);
}

IMP_LIST_IMPL(ListGroupnameContainer, Classname,
              classname, Value,, {
                if (sorted_) std::sort(classnames_begin(),
                                       classnames_end());
              },);


void ListGroupnameContainer::set_is_editing(bool tf) {
  if (tf== !sorted_) return;
  else {
    sorted_=!tf;
    if (sorted_) {
      std::sort(classnames_begin(), classnames_end());
    }
  }
}


bool
ListGroupnameContainer::get_contains_classname(Value vt) const {
  IMP_CHECK_OBJECT(this);
  return std::binary_search(classnames_begin(), classnames_end(), vt);
}

void ListGroupnameContainer::show(std::ostream &out) const {
  IMP_CHECK_OBJECT(this);
  out << "ListGroupnameContainer with " << get_number_of_classnames()
      << " classnames." << std::endl;
}

IMPCORE_END_NAMESPACE
