/**
 *  \file MinimumGroupnameScoreRestraint.cpp
 *  \brief The minimum score over a container.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/MinimumGroupnameScoreRestraint.h"
#include "IMP/core/internal/MinimalSet.h"
#include "IMP/core/internal/container_helpers.h"


IMPCORE_BEGIN_NAMESPACE

MinimumGroupnameScoreRestraint
::MinimumGroupnameScoreRestraint(GroupnameScore *f,
                                 GroupnameContainer *c,
                                 unsigned int n): f_(f), c_(c), n_(n){
}

namespace {
  typedef internal::MinimalSet<float,
    GroupnameContainer::ClassnameIterator> MS;
  template <class It, class F>
  MS find_minimal_set(It b, It e, F *f, unsigned int n) {
    IMP_LOG(TERSE, "Finding lowest " << n << " of "
            << std::distance(b,e) << std::endl);
    MS bestn(n);
    for (It it= b; it != e; ++it) {
      float score= internal::ContainerTraits<Classname>
                           ::evaluate(f, *it, NULL);

      if (bestn.can_insert(score)) {
        bestn.insert(score, it);
      }
    }
    return bestn;
  }
}


MinimumGroupnameScoreRestraint::~MinimumGroupnameScoreRestraint(){}

Float MinimumGroupnameScoreRestraint
::evaluate(DerivativeAccumulator *da) {
  MS bestn= find_minimal_set(c_->classnames_begin(),
                             c_->classnames_end(), f_.get(), n_);

  float score=0;
  for (unsigned int i=0; i< bestn.size(); ++i) {
    if (da) {
      internal::ContainerTraits<Classname>::evaluate(f_.get(),
                                                     *bestn[i].second, da);
    }
    score+= bestn[i].first;
  }

  return score;
}

void MinimumGroupnameScoreRestraint::show(std::ostream &out) const {
  out << "MinimumGroupnameScoreRestraint over ";
  c_->show(out);
  out << " using function ";
  f_->show(out);
  out << std::endl;
}


ParticlesList MinimumGroupnameScoreRestraint::get_interacting_particles() const
{
  MS bestn= find_minimal_set(c_->classnames_begin(),
                             c_->classnames_end(), f_.get(), n_);
  ParticlesList ret;
  for (unsigned int i=0; i< bestn.size(); ++i) {
    Particles c= internal::ContainerTraits<Classname>
                 ::create_set(*bestn[i].second);
    ret.push_back(c);
  }

  return ret;
}
IMPCORE_END_NAMESPACE
