/**
 *  \file GroupnameScore.h    \brief Define GroupnameScore.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 */

#ifndef IMP_GROUPNAME_SCORE_H
#define IMP_GROUPNAME_SCORE_H

#include "config.h"
#include "base_types.h"
#include "RefCounted.h"
#include "Particle.h"
#include "DerivativeAccumulator.h"

IMP_BEGIN_NAMESPACE

//! Abstract score function
/** GroupnameScores will evaluate the score and derivatives
    for the passed particles. Use in conjunction with various
    restraints such as IMP::core::GroupnamesRestraint or
    IMP::core::GroupnameRestraint.

    Implementers should check out IMP_GROUPNAME_SCORE().
*/
class IMPEXPORT GroupnameScore : public Object
{
public:
  GroupnameScore(std::string name="GroupnameScore %1%");
  //! Compute the score and the derivative if needed.
  virtual Float evaluate(ClassnameArguments,
                         DerivativeAccumulator *da) const = 0;
  IMP_REF_COUNTED_DESTRUCTOR(GroupnameScore)
};

IMP_OUTPUT_OPERATOR(GroupnameScore);

IMP_END_NAMESPACE

#endif  /* IMP_GROUPNAME_SCORE_H */
