/**
 *  \file GroupnameContainerSet.h
 *  \brief Store a set of GroupnameContainers
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 */

#ifndef IMPCORE_GROUPNAME_CONTAINER_SET_H
#define IMPCORE_GROUPNAME_CONTAINER_SET_H

#include "config.h"
#include "internal/version_info.h"
#include <IMP/GroupnameContainer.h>
#include <IMP/container_macros.h>

IMPCORE_BEGIN_NAMESPACE

//! Stores a set of GroupnameContainers
/**
 */
class IMPCOREEXPORT GroupnameContainerSet
  : public GroupnameContainer
{
public:
  //! Construct and empty set
  GroupnameContainerSet();

  IMP_GROUPNAME_CONTAINER(GroupnameContainerSet, internal::version_info);

  IMP_LIST(public, GroupnameContainer, groupname_container,
           GroupnameContainer*);
};


IMPCORE_END_NAMESPACE

#endif  /* IMPCORE_GROUPNAME_CONTAINER_SET_H */
