/**
 *  \file GroupnamesScoreState.h
 *  \brief Use a GroupnameModifier applied to a Classnames to
 *  maintain an invariant
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 */

#ifndef IMPCORE_GROUPNAMES_SCORE_STATE_H
#define IMPCORE_GROUPNAMES_SCORE_STATE_H

#include "core_exports.h"
#include "GroupnameContainer.h"
#include "GroupnameModifier.h"
#include "internal/core_version_info.h"

#include <IMP/ScoreState.h>

IMPCORE_BEGIN_NAMESPACE

// for swig
class GroupnameContainer;
class GroupnameModifier;

//! Apply a GroupnameFunction to a GroupnameContainer to maintain an invariant
/** \ingroup restraint
 */
class IMPCOREEXPORT GroupnamesScoreState : public ScoreState
{
  Pointer<GroupnameModifier> f_;
  Pointer<GroupnameContainer> c_;
public:
  GroupnamesScoreState(GroupnameModifier *f, GroupnameContainer *c);

  virtual ~GroupnamesScoreState();

  IMP_SCORE_STATE(internal::core_version_info)
};


IMPCORE_END_NAMESPACE

#endif  /* IMPCORE_GROUPNAMES_SCORE_STATE_H */
