/**
 *  \file GroupnamesScoreState.cpp
 *  \brief Use a GroupnameModifier applied to a GroupnameContainer to
 *  maintain an invariant
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/GroupnamesScoreState.h"
#include "IMP/core/internal/container_helpers.h"

IMPCORE_BEGIN_NAMESPACE

GroupnamesScoreState::GroupnamesScoreState(GroupnameModifier *f,
                                           GroupnameContainer *c):
  f_(f), c_(c){
}

GroupnamesScoreState::~GroupnamesScoreState(){}


void GroupnamesScoreState::do_before_evaluate()
{
  IMP_LOG(TERSE, "Begin GroupnamesScoreState::evaluate" << std::endl);
  IMP_CHECK_OBJECT(f_);
  IMP_CHECK_OBJECT(c_);
  for (GroupnameContainer::ClassnameIterator
       it= c_->classnames_begin();
       it != c_->classnames_end(); ++it) {
    IMP_LOG(VERBOSE, "Applying"<< std::endl);

    // Need the .get for template matching
    internal::ContainerTraits<Classname>::apply(f_.get(), *it);
  }
  IMP_LOG(TERSE, "End GroupnamesScoreState::evaluate" << std::endl);
}


void GroupnamesScoreState::show(std::ostream &out) const {
  out << "GroupnamesScoreState base" << std::endl;
}

IMPCORE_END_NAMESPACE
