Import('env')

files = [
         'CommonEndpointPairFilter.cpp',
         'LowestRefinedPairScore.cpp',
         'RefineOncePairScore.cpp',
         'StateAdaptor.cpp',
         'attribute_statistics.cpp',
         'interaction_graph.cpp',
        ]

# Build and install the shared library:
env.IMPModuleLib(files)
