Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'LowestRefinedPairScore.cpp',
         'RefineOncePairScore.cpp',
         'TunnelSingletonScore.cpp',
         'text_manipulation.cpp',
         'attribute_statistics.cpp',
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
