/**
 *  \file MinimumPairScore.h    \brief Define PairScore.
 *
 *  This file is generated by a script (tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 Sali Lab. All rights reserved.
 */

#ifndef IMPCORE_MINIMUM_PAIR_SCORE_H
#define IMPCORE_MINIMUM_PAIR_SCORE_H

#include "config.h"
#include <IMP/PairScore.h>

IMPCORE_BEGIN_NAMESPACE

//! Evaluate the minimum n pair scores of the passed set of PairScores
/** Each of the set of PairScores is evaluated and the sum of the
    minimum n is returned.
*/
class IMPCOREEXPORT MinimumPairScore : public PairScore
{
  PairScores scores_;
  unsigned int n_;
public:
  MinimumPairScore(const PairScoresTemp &scores,
                       unsigned int n=1,
                       std::string name="PairScore %1%");
  IMP_PAIR_SCORE(MinimumPairScore, get_module_version_info());
};

IMPCORE_END_NAMESPACE

#endif  /* IMPCORE_MINIMUM_PAIR_SCORE_H */
