/**
 *  \file PairsOptimizerState.h
 *  \brief Use a PairModifier applied to a ParticlePairs to
 *  maintain an invariant
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 */

#ifndef IMPCORE_PAIRS_OPTIMIZER_STATE_H
#define IMPCORE_PAIRS_OPTIMIZER_STATE_H

#include "config.h"
#include "internal/version_info.h"
#include <IMP/PairContainer.h>
#include <IMP/PairModifier.h>
#include <IMP/OptimizerState.h>

IMP_BEGIN_NAMESPACE
// for swig
class PairContainer;
class PairModifier;
IMP_END_NAMESPACE

IMPCORE_BEGIN_NAMESPACE
//! Apply a PairFunction to a PairContainer to maintain an invariant
/** \ingroup restraint
    \see PairOptimizerState
 */
class IMPCOREEXPORT PairsOptimizerState : public OptimizerState
{
  Pointer<PairModifier> f_;
  Pointer<PairContainer> c_;
public:
  /** \param[in] c The Container to hold the elements to process
      \param[in] gf The PairModifier to apply to all elements.
      \param[in] name The name to use for this Object
   */
  PairsOptimizerState(PairContainer *c, PairModifier *gf,
                           std::string name="PairsOptimizerState %1%");

  IMP_OPTIMIZER_STATE(PairsOptimizerState, internal::version_info)
};


IMPCORE_END_NAMESPACE

#endif  /* IMPCORE_PAIRS_OPTIMIZER_STATE_H */
