Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Elina Tjioe", "Keren Lasker", "Jeremy Phillips", "Ben Webb"],
                 brief="""MODULENAME provides a higher level interface for using experimental proteomics data with \\imp""",
                 overview="""\\section i1 Introduction

Restrainer is an IMP module that provides convenient way of inputting molecule
definition and experimental data into \\imp. This module will take experimental
data in XML format, and translate it into \\imp restraints to construct models at
a variety of different resolutions or levels.

The XML input data is divided into 3 parts:
 -# Representation
      - Each component in the system can have either atomic or geometric shape representation.
 -# RestraintSet
      - Restraint can be added for each component, between and among components in the representation.
 -# Display
      - Colors for the representation components can be defined and an output file can be generated in chimera format.

The XML schema is provided to check the validation of the input data. The visualization of the XML schema can be seen
<a href="../../modules/restrainer/test/input/IMP_Schema.png" target="_blank">here</a>.

To check if the XML files are valid use the \c schema.xsd which can be found as part of the restrainer data.
\code
xmllint --schema schema.xsd --noout *.xml
\endcode

The process of preparing the input data for %restrainer can be best shown on the <a href="IMP_restrainer_examples.html">IMP.restrainer examples</a> page.

\section i2 Namespace Reference
- <a href="classIMP_1_1restrainer_1_1xml__parser_1_1XMLRepresentation.html">XMLRepresentation Class</a>
- <a href="classIMP_1_1restrainer_1_1xml__parser_1_1XMLRestraint.html">XMLRestraint Class</a>
- <a href="classIMP_1_1restrainer_1_1xml__parser_1_1XMLDisplay.html">XMLDisplay Class</a>
- <a href="classIMP_1_1restrainer_1_1representation_1_1Representation.html">Representation Class</a>
- <a href="classIMP_1_1restrainer_1_1restraint_1_1Restraint.html">Restraint Class</a>
- <a href="classIMP_1_1restrainer_1_1display_1_1Display.html">Display Class</a>""",
                 license=None,
                 publications=env.StandardPublications())
