Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Elina Tjioe", "Keren Lasker", "Jeremy Phillips", "Ben Webb"],
                 brief="""MODULENAME provides a higher level interface for using experimental proteomics data with \\imp""",
                 overview="""MODULENAME provides convenient way of inputting molecule definition and experimental data into \imp.""",
                 license=None,
                 publications=env.StandardPublications())
