/**
 *  \file ListQuadContainer.cpp   \brief A list of ParticleQuadsTemp.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2011 IMP Inventors. All rights reserved.
 *
 */

#include <IMP/core/internal/quad_helpers.h>
#include <IMP/QuadModifier.h>
#include <IMP/QuadScore.h>

IMPCORE_BEGIN_INTERNAL_NAMESPACE

unsigned int ListLikeQuadContainer
::get_number_of_particle_quads() const {
  IMP_CHECK_OBJECT(this);
  IMP_USAGE_CHECK(get_is_up_to_date(),
                  "Attempting to use container "
                  << get_name() << " that is not up to date."
                  << " Call Model::evaluate() first, or something is broken.");
  return data_.size();
}
bool ListLikeQuadContainer
::get_contains_particle_quad(const ParticleQuad& vt) const {
  IMP_CHECK_OBJECT(this);
  update_index();
  return index_.find(vt)!= index_.end();
}

ParticleQuad ListLikeQuadContainer
::get_particle_quad(unsigned int i) const {
  IMP_CHECK_OBJECT(this);
  return data_[i];
}

void ListLikeQuadContainer
::do_show(std::ostream &out) const {
  out << "contains " << data_.size() << std::endl;
}


ParticlesTemp ListLikeQuadContainer
::get_contained_particles() const {
  return IMP::internal::flatten(data_);
}

bool ListLikeQuadContainer
::get_contained_particles_changed() const {
  return changed_;
}

QuadContainerPair ListLikeQuadContainer
::get_added_and_removed_containers() const {
  return QuadContainerPair(new ListLikeQuadContainer(),
                                new ListLikeQuadContainer());
}

IMPCORE_END_INTERNAL_NAMESPACE
