files = [
         'ArrayOnAttributesHelper.cpp',
         'CoreClosePairContainer.cpp',
         'CoreListPairContainer.cpp',
         'CoreListQuadContainer.cpp',
         'CoreListSingletonContainer.cpp',
         'CoreListTripletContainer.cpp',
         'CorePairsRestraint.cpp',
         'CoreQuadsRestraint.cpp',
         'CoreSingletonsRestraint.cpp',
         'CoreTripletsRestraint.cpp',
         'DifferenceSingletonContainer.cpp',
         'MovedSingletonContainer.cpp',
         'ParticleGrid.cpp',
         'graph_base.cpp',
         'pair_helpers.cpp',
         'quad_helpers.cpp',
         'rigid_body_tree.cpp',
         'singleton_helpers.cpp',
         'triplet_helpers.cpp',
        ]

files = [File(x) for x in files]
Return('files')
