files = [
         'ArrayOnAttributesHelper.cpp',
         'DifferenceSingletonContainer.cpp',
         'MovedSingletonContainer.cpp',
         'ParticleGrid.cpp',
         'graph_base.cpp',
         'pair_helpers.cpp',
         'rigid_body_tree.cpp',
         'singleton_helpers.cpp',
        ]

files = [File(x) for x in files]
Return('files')
