Import('env')

env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  show_exceptions=['RefCounted',
                                   'RandomNumberGenerator',],
                  function_name_exceptions=['Particle.has_attribute', 'Model.restore_particle',
                                            'RandomNumberGenerator.seed'],
                  value_object_exceptions=[ 'Exception','IOException', 'IndexException',
                                           'InternalException', 'ModelException', 'PairFunctor',
                                           'QuadFunctor', 'RandomNumberGenerator', 'RefCounted',
                                           'ValueException', 'WarningContext',
                                           'FailureHandlerBase', "TextInput", "TextOutput"],
                  spelling_exceptions=['altgraph'])
