Import('env')
import scons_tools.gcc

if env['CXX'] == 'g++':
    cxxflags=['-fno-finite-math-only',
              '-ftrapping-math',
              '-fsignaling-nans',
              '-fno-float-store']
    if scons_tools.gcc.get_version(env)>= 4.3:
        cxxflags==cxxflags+['-fsigned-zeros',
                            '-fno-reciprocal-math',
                            '-fno-associative-math']
else:
    cxxflags=[]
env.IMPModuleBuild(version='SVN',
                   required_dependencies=["CGAL"],
                   cxxflags=cxxflags)
