files = ['BondedListScoreState.h', 'NonbondedListScoreState.h',
         'BipartiteNonbondedListScoreState.h', 'MaxChangeScoreState.h',
         'BondDecoratorListScoreState.h', 'AllNonbondedListScoreState.h',
         'GravityCenterScoreState.h']

files = [File(f) for f in files]
Return('files')
