Import('env')

files = ('CombState.h', 'JNode.h', 'SimpleDiscreteRestraint.h',
         'DiscreteSampler.h','SimpleDiscreteSpace.h', 'DominoOptimizer.h',
         'RestraintGraph.h','JEdge.h')

# Install the include files:
env.IMPHeaders(files)
