WEB=${WEBTOP}
FILES=${WEB}/index.html ${WEB}/contact.html ${WEB}/developers.html
INSTFILES=alber_fig_5b.jpg hybrid.jpg imp_banner.jpg imp.css \
          exp_cycle.png hybrid.png
TOPDIR=.
SUBDIRS=

include ${TOPDIR}/Makefile.include
