WEBTOP=~www/html/imp
INCLUDE=${TOPDIR}/functions.inc

.PHONY: all ${SUBDIRS}

all: ${FILES} ${INSTFILES} ${SUBDIRS}
	@if [ ! -d ${WEB} ]; then mkdir -p ${WEB}; fi
	install ${INSTFILES} ${WEB}

${WEB}/%.html: %.php ${INCLUDE}
	php -d include_path="${TOPDIR}" < $< > $@

${SUBDIRS}:
	${MAKE} -C $@
