Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'KMData.cpp',
         'KMCenters.cpp',
         'KMFilterCenters.cpp',
         'KMCentersTree.cpp',
         'KMCentersNode.cpp',
         'KMCentersNodeSplit.cpp',
         'KMCentersNodeLeaf.cpp',
         'KMRectangle.cpp',
         'KMLocalSearch.cpp',
         'KMLocalSearchLloyd.cpp',
         'KMLProxy.cpp',
         'CombState.cpp',
         'DominoOptimizer.cpp',
         'JEdge.cpp',
         'JNode.cpp',
         'RestraintGraph.cpp',
         'DiscreteSet.cpp',
         'PermutationSampler.cpp',
         'MappedDiscreteSet.cpp',
         'CartesianProductSampler.cpp',
         'SymmetrySampler.cpp',
         'TransformationUtils.cpp',
         'TransformationMappedDiscreteSet.cpp',
         'TransformationCartesianProductSampler.cpp',
         'TransformationPermutationSampler.cpp',
         'SimpleDiscreteRestraint.cpp',
         'SimpleDiscreteSpace.cpp',
         'TransformationDiscreteSet.cpp',
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
