from tools import embed

Import('env', 'invalidate_environment')

# Get custom environment for building against EMBED:
emenv = env.Clone()
embed.configure_check(emenv)
Export('emenv')

# Make sure that all builds with this environment fail if EMBED was not found:
if emenv['EM_LIBS'] == '' or emenv['MODELLER_LIBS'] == '':
    invalidate_environment(emenv, embed.fail)

# Subdirectories:
lib = SConscript('src/SConscript')
SConscript('include/SConscript')
pyext = SConscript('pyext/SConscript')
test = SConscript('test/SConscript')
emenv.Depends(test, [pyext, lib])

Return('lib')
