Import('env')

files = ['Harmonic.cpp', 'HarmonicLowerBound.cpp', 'HarmonicUpperBound.cpp',
         'OpenCubicSpline.cpp', 'ClosedCubicSpline.cpp', 'Cosine.cpp']

files = [File(x) for x in files]
Return('files')
