Import('env')


env= env.IMPApplication(required_modules=['atom'],
                        required_dependencies=['Boost.ProgramOptions', 'Boost.FileSystem'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="ligand_score", source=["ligand_score.cpp"])
