import os.path
Import('env')

files = ['noncopyable.h']


# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'decorators')
inst = env.Install(includedir, files)
env.Alias('install', inst)
