Import('env')

files = ['CoarseEMRestraint.cpp', 'PairConnectivityRestraint.cpp', 
         'ConnectivityRestraint.cpp', 'ProximityRestraint.cpp',
         'CoordinateRestraint.cpp', 'Restraint.cpp', 'RestraintSet.cpp',
	 'DistanceRestraint.cpp', 'TorusRestraint.cpp', 
	 'ExclusionVolumeRestraint.cpp']

files = [File(x) for x in files]
Return('files')
