Import('env')

e = env.IMPSharedLibraryEnvironment()

files = ('CombState.cpp', 'JNode.cpp', 'JEdge.cpp',
         'RestraintGraph.cpp', 'DominoOptimizer.cpp',
         'SimpleDiscreteRestraint.cpp')

# Build and install the shared library:
lib, libinst = e.IMPSharedLibrary(files, install=True)

Return('lib')
