Import('env', 'get_sharedlib_environment', 'ver_cpp')

# Get an environment suitable for building a shared library:
e = get_sharedlib_environment(env, 'IMPDOMINO_EXPORTS', cplusplus=True)

e.Append(CPPPATH=['#/build/include', e['BOOST_CPPPATH']])
e.Append(LIBPATH=['#/build/libs'], LIBS=['imp'])

files = ('CombState.cpp', 'JNode.cpp', 'JEdge.cpp', 'RestraintGraph.cpp',
         'DominoOptimizer.cpp', 'SimpleDiscreteRestraint.cpp', ver_cpp)

# Build the shared library:
lib = e.SharedLibrary('#/build/libs/imp_domino', files)
e.Alias('domino', lib)

# Install the library:
libinst = e.Install(e['libdir'], lib)
e.Alias('domino-install', [libinst])

Return('lib')
