Import('env')
Export('env')

env.Append(LIBS=['imp_core', 'imp_algebra'])
env.validate()

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
SConscript('bin/SConscript')
