import os.path
Import('env')

files = ['ConjugateGradients.h', 'Optimizer.h', 'SteepestDescent.h',
         'MolecularDynamics.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'optimizers')
inst = env.Install(includedir, files)
env.Alias('install', inst)
