Import('env')

files = [
         'Distribution.h',
         'FormFactorTable.h',
         'Profile.h',
         'Restraint.h',
         'Score.h',
         'SolventAccessibleSurface.h',
         'utility.h']

# Install the include files:
env.IMPModuleInclude(files)
