Import('env')

files = [
         'FormFactorTable.h',
         'RadialDistributionFunction.h',
         'SAXSProfile.h',
         'SaxsData.h',
        ]

# Install the include files:
env.IMPHeaders(files)
