#!/usr/bin/python

import os
import os.path
import sys
import getopt
import shutil
import re
import datetime
version=

def main():
    # check exists
    open("VERSION", "r")
    open("VERSION", "w").write("nightly-"+str(datetime.date.today().day)\
                                   +"/"+str(datetime.date.today().month)\
                                   +"/"+str(datetime.date.today().year))


if __name__ == '__main__':
    main()
