Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Daniel Russel"],
                 brief="MODULENAME contains miscellaneous and experimental functionality.",
                 overview="""MODULENAME contains miscellaneous functionality that is <b>not</b> expected to be used by many \\imp users. As a result, the code contained in it may be poorly tested, liable to change or experimental in nature.
<br><br>
In particular, other modules should <b>not</b> depend on %IMP.%misc (e.g. don't create a class in another module that derives from one in %IMP.%misc). If you find yourself relying on such functionality, discuss moving it to a specialized module or something like IMP.core or IMP.atom.""",
                 publications="None",
                 license="None")
