/**
 *  \file IMP/container/CLASSNAMEContainerSet.h
 *  \brief Store a set of CLASSNAMEContainers
 *
 *  This file is generated by a script (tools/maintenance/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 */

#ifndef IMPCONTAINER_HEADERNAME_CONTAINER_SET_H
#define IMPCONTAINER_HEADERNAME_CONTAINER_SET_H

#include <IMP/container/container_config.h>
#include <IMP/CLASSNAMEContainer.h>
#include <IMP/container_macros.h>
#include <IMP/internal/container_helpers.h>
#include <IMP/scoped.h>

IMPCONTAINER_BEGIN_NAMESPACE

//! Stores a set of CLASSNAMEContainers
/** The input sets must be disjoint. This can change if there is
    demand for it.

    \usesconstraint
*/
class IMPCONTAINEREXPORT CLASSNAMEContainerSet
  : public CLASSNAMEContainer
{
  static CLASSNAMEContainerSet* get_set(CLASSNAMEContainer* c) {
    return dynamic_cast<CLASSNAMEContainerSet*>(c);
  }
 public:
  //! Construct and empty set
  CLASSNAMEContainerSet(Model *m,
                        std::string name="CLASSNAMEContainerSet %1%");

  CLASSNAMEContainerSet(const CLASSNAMEContainersTemp &pc,
                        std::string name="CLASSNAMEContainerSet %1%");

  /** \brief apply modifer sm to all LCCLASSNAME containers */
  IMP_IMPLEMENT(void do_apply(const CLASSNAMEModifier *sm) const);

  template <class M>
      void apply_generic(const M*m) const {
    apply(m);
  }

  ParticleIndexes get_all_possible_indexes() const;
  IMP_OBJECT(CLASSNAMEContainerSet);

  /** @name Methods to control the nested container

      This container merges a set of nested containers. To add
      or remove nested containers, use the methods below.
  */
  /**@{*/
  IMP_LIST_ACTION(public, CLASSNAMEContainer, CLASSNAMEContainers,
                  CLASSFUNCTIONNAME_container, CLASSFUNCTIONNAME_containers,
                  CLASSNAMEContainer*, CLASSNAMEContainers,
                  {
                    obj->set_was_used(true);
                    set_is_changed(true);
                  },{},
                  );
  /**@}*/

#ifndef IMP_DOXYGEN
  PLURALINDEXTYPE get_indexes() const;
  PLURALINDEXTYPE get_range_indexes() const;
  ModelObjectsTemp do_get_inputs() const;
#endif

  IMP_IMPLEMENT(void do_before_evaluate());
};


IMPCONTAINER_END_NAMESPACE

#endif  /* IMPCONTAINER_HEADERNAME_CONTAINER_SET_H */
