Import('env')

files = ['AtomDecorator.cpp', 'bond_decorators.cpp',
         'HierarchyDecorator.cpp', 'NameDecorator.cpp', 'ResidueDecorator.cpp',
         'MolecularHierarchyDecorator.cpp', 'XYZDecorator.cpp']

files = [File(x) for x in files]
Return('files')
