Import('env')
import scons_tools.examples

env= env.IMPSystem(name="Example Biological System", version="SVN",
                   authors=["Daniel Russel"],
                   brief="Solve a simplified Nup84 complex.",
                   overview="""See \\ref example_sys_callgraphs "callgraphs" for the callgraphs
                   of the scripts and \\ref Example_system_code "example system code" to review
                   the code.
                   """,
                   license=env.IMPStandardLicense(),
                   publications=[],
                   required_modules=['core', 'atom'])
if env:
    files= ["setup",
            "sample_0",
            "analyze_0"]
    scons_tools.examples.add_python_example(env, "setup.py",
                                            "General setup code common to sampling and analysis.")
    scons_tools.examples.add_python_example(env, "sample_0.py",
                                            "Sampling using MCCG and random starting points.")
    scons_tools.examples.add_python_example(env, "analyze_0.py",
                                            "Cluster into 10 solutions.")
    scons_tools.examples.add_page(env, "Example system code",
                                  [x+".py" for x in files])
