/**
 *  \file PairFilter.cpp   \brief Filter for particle_pair.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 Sali Lab. All rights reserved.
 *
 */

#include "IMP/container/InContainerPairFilter.h"

IMPCONTAINER_BEGIN_NAMESPACE


InContainerPairFilter
::InContainerPairFilter(PairContainer *c,
                             std::string name): PairFilter(name), c_(c){}

bool InContainerPairFilter
::get_contains_particle_pair(const ParticlePair& p) const {
  return c_->get_contains_particle_pair(p);
}

ParticlesTemp InContainerPairFilter
::get_input_particles(const ParticlePair&) const {
  // not quite right, but...
  return ParticlesTemp();
}
ContainersTemp InContainerPairFilter
::get_input_containers(const ParticlePair&) const {
  return ContainersTemp(1,c_);
}

void InContainerPairFilter::do_show(std::ostream &out) const {
  out << "InContainerPairFilter on " << *c_ << std::endl;
}

IMPCONTAINER_END_NAMESPACE
