/**
 *  \file TripletFilter.cpp   \brief Filter for triplet.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 Sali Lab. All rights reserved.
 *
 */

#include "IMP/container/InContainerTripletFilter.h"

IMPCONTAINER_BEGIN_NAMESPACE


InContainerTripletFilter
::InContainerTripletFilter(TripletContainer *c,
                             std::string name): TripletPredicate(name)
{
  c_=new internal::TripletContainerIndex(c, true);
}


InContainerTripletFilter
::InContainerTripletFilter(TripletContainer *c,
                             bool handle_permutations,
                             std::string name): TripletPredicate(name)
{
  c_=new internal::TripletContainerIndex(c, handle_permutations);
}


IMPCONTAINER_END_NAMESPACE
