Import('env','modconfig')


# Source files
files = ('MapReaderWriter.cc','DensityHeader.cc','Map3D.cc','DensityMap.cc','EMReaderWriter.cc','XplorReaderWriter.cc','MRCReaderWriter.cc','SampledDensityMap.cc','CoarseCC.cc','CoarseCCatIntervals.cc')

# Header files - for win
#headers = ('def.h','MapReaderWriter.h','DensityHeader.h','Map3D.h','DensityMap.h','EMReaderWriter.h','XplorReaderWriter.h','CoarseCCatIntervals.h'))

# Build a Windows DLL exports file from the public header files:
#not relevant ( at least now)
#env.W32Def('libem.def', headers)

# Build the shared library:
lib = env.SharedLibrary('emlib', files)
#additional parametesr for windows
# WIN32DEFPREFIX='lib',
#                        WIN32_INSERT_DEF=1, WINDOWSEXPPREFIX='lib')

# Install the library:

libinst = env.Install(modconfig['libinstall'], lib)
env.Alias('install', [libinst])

# Subdirectories:
pyext = SConscript('pyext/SConscript')

Return('lib', 'pyext')
