Import('env')

files = [
         'KMCenters.h',
         'KMCentersNode.h',
         'KMCentersNodeLeaf.h',
         'KMCentersNodeSplit.h',
         'KMCentersTree.h',
         'KMData.h',
         'KMFilterCenters.h',
         'KMLProxy.h',
         'KMLocalSearch.h',
         'KMLocalSearchLloyd.h',
         'KMRectangle.h',
         'KMTerminationCondition.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
