Import('env')

files = [
         'Histogram.h',
         'MoveStatisticsScoreState.h',
         'PartitionalClustering.h',
         'point_clustering.h',
         'statistics_macros.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
