files = [
         'PrefixStream.cpp',
         'constants.cpp',
         'deprecation.cpp',
         'directories.cpp',
         'particle_save.cpp',
         'static.cpp',
         'swig.cpp',
        ]

files = [File(x) for x in files]
Return('files')
