Import('env')

files = ['graph_base.cpp', 'ParticleGrid.cpp', 'Object.cpp',
         'kernel_version_info.cpp', 'constants.cpp', 'bbox_nbl_helpers.cpp']

files = [File(x) for x in files]
Return('files')
