Import('env')

e = env.IMPPythonExtensionEnvironment()
e.Append(CPPDEFINES=['SWIG_WRAPPER'])

e.IMPPythonExtension('algebra.i')

files = (Glob('algebra/*.py'))

# Install the Python files:
env.IMPPython(files)
