Import('env', 'modconfig', 'pythoninc', 'configure_for_pyext',
       'is_wine_platform')

# Source files
files = ('Score_Func.cpp', 'Model.cpp', 'Model_Data.cpp', 'Optimizer.cpp',
         'Particle.cpp', 'Restraint_Set.cpp', 'Restraint.cpp',
         'Complexes_Restraints.cpp', 'Rigid_Body.cpp', 'log.cpp', 'imp.cpp')

# Build the shared library:
lib = env.SharedLibrary('imp', files)

# Install the library:
libinst = env.Install(modconfig['libinstall'], lib)
env.Alias('install', [libinst])

# Subdirectories:
pyext = SConscript('pyext/SConscript')
test = SConscript('tests/SConscript')
env.Depends(test, lib)

Return('lib', 'pyext')
