Import('env')

files = ['AtomDecorator.cpp', 'bond_decorators.cpp', 'graph_base.cpp',
         'HierarchyDecorator.cpp', 'NameDecorator.cpp',
         'MolecularHierarchyDecorator.cpp']

files = [File(x) for x in files]
Return('files')
