Import("env")

files = [
  "opencv_interface.cpp",
  "align2D.cpp" ,
  "labeling_algorithm.cpp" ,
  "ProjectionFinder.cpp" ,
  "model_interaction.cpp" ,
  "project.cpp" ,
  "image_processing.cpp" ,
  "pca_features_extraction.cpp" ,
  "RegistrationResult.cpp" ,
  "FFToperations.cpp" ,
  "ProjectionMask.cpp" ,
  "Fine2DRegistrationRestraint.cpp" ,
  "ProjectionParameters.cpp" ,
  "scores2D.cpp" ,
  "Em2DRestraint.cpp",
  "Image.cpp",
  "TransformationsCluster.cpp",
  "cluster_of_models.cpp"
          ]\
        + SConscript("internal/SConscript")

# Build and install the shared library:
env.IMPModuleLib(files)
