Import("env")

files = [
  "opencv_interface.cpp",
  "align2D.cpp" ,
  "ProjectionFinder.cpp" ,
  "model_interaction.cpp" ,
  "project.cpp" ,
  "image_processing.cpp" ,
  "pca_features_extraction.cpp" ,
  "RegistrationResult.cpp" ,
  "FFToperations.cpp" ,
  "ProjectionMask.cpp" ,
  "Fine2DRegistrationRestraint.cpp" ,
  "ProjectionParameters.cpp" ,
  "scores2D.cpp" ,
  "Em2DRestraint.cpp",
  "Image.cpp",
  "hierarchical_clustering.cpp",
  "CollisionCrossSection.cpp",
  "domino_particle_states.cpp",
  "domino_filters.cpp",
  "domino_filter_tables.cpp",

          ]\
        + SConscript("internal/SConscript")

# Build and install the shared library:
env.IMPModuleLib(files)
