Import('env')

# Get a modified build environment suitable for building Python extensions:
e = env.IMPPythonExtensionEnvironment()

# Build the Python extension from SWIG interface file:
e.IMPPythonExtension('em.i')
