Import('env')

env.IMPModuleAbout(author='Dina Schneidman and Seung Joong Kim', version='SVN',
                   description='Small Angle X-ray Scattering methods.')

# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Append(LIBS=env['CGAL_LIBS'])


env.Append(LIBS=['imp_core', 'imp_algebra', 'imp_atom'])
env.validate()

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
SConscript('data/SConscript', exports='env')
