Import('env')

env.IMPModuleAbout(author='Dina Schneidman and Seung Joong Kim', version='SVN',
                   description='Small Angle X-ray Scattering methods.')

env.Append(LIBS=['imp_core', 'imp_algebra', 'imp_atom'])
env.validate()

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
