Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Dina Schneidman", "Seung Joong Kim"],
                 brief="This module adds small angle X-ray scattering support to \\imp",
                 overview="",
                 publications=env.IMPStandardPublications(),
                 license=env.IMPStandardLicense())
