Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Dina Schneidman", "Seung Joong Kim"],
                 brief="MODULENAME adds small angle X-ray scattering support to \\imp",
                 overview=None,
                 publications=env.IMPStandardPublications(),
                 license=env.IMPStandardLicense())
