Import('env')
import scons_tools.dependency.boost
scons_tools.dependency.boost.add_boost_library(env, "ProgramOptions", "program_options", 'boost/program_options.hpp',
                                               extra_boost_libs=["system"])



env= env.IMPApplication(required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="foxs", source=["profile.cpp", "Gnuplot.cpp", "ColorCoder.cpp", "JmolWriter.cpp"])
#    env.IMPCPPExecutable(target="foxsm", source=["profile_michal.cpp", "Gnuplot.cpp"])
#    env.IMPCPPExecutable(target="foxs_water", source=["profile_water.cpp", "Gnuplot.cpp"])
#    env.IMPCPPExecutable(target="foxs_mixture", source=["profile_mixture.cpp", "Gnuplot.cpp"])
#    env.IMPCPPExecutable(target="foxs2", source=["profile2.cpp", "Gnuplot.cpp"])
