Import('env')

env= env.IMPApplication(name="foxs", version="SVN",
                        authors=["Dina Schneidman"],
                        brief="Compute the scattering profile of an assembly",
                        overview="",
                        license=env.IMPStandardLicense(),
                        publications=[],
                        required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="foxs", source=["profile.cpp", "Gnuplot.cpp"])
