Import('env')

applications=['foxsdock',
              'nmr_rtc',
              'em2d_dock',
              'em3d_dock']

if env.get('local', False):
    for d in Glob("*/SConscript"):
        p= str(d).split("/")[0]
        if not p in applications:
            applications.append(p)

for p in applications:
    SConscript(p+"/SConscript")
