#!/bin/sh

if test -e .git; then
git pull
cd tools/git/config
for i in */*
do
ln -s ../../tools/git/config/$i ../../../.git/$i
done
cd ../../..
git checkout develop
git checkout -b master origin/master
echo "




" | git flow init
else

echo "Script must be run from git root"
fi
