Import('env')

systems=['groel']

if env.get('local', False):
    for d in Glob("*/SConscript"):
        p= str(d).split("/")[0]
        if not p in systems:
            systems.append(p)

for p in systems:
    SConscript(p+"/SConscript")
