#!/bin/sh

if test -e .git; then
git checkout develop
git pull origin develop
git checkout nightly
git merge -s ours develop -m "nightly update"
date=`date --rfc-3339=date`
echo nightly-$date > VERSION
echo "Nightly build of IMP on $date. This branch is updated each night in conjunction with the automated builds and tests."> README.md
git commit README.md VERSION -m "nightly branch update"
git push origin nightly

else

echo "Script must be run from git root"
fi
