Import('env')

files = ['IMP.h']

# Place in build directory:
env.Install('#/build/include', files)

# Install the include files:
includedir = env['includedir']
inst = env.Install(includedir, files)
env.Alias('install', inst)

# Subdirectories
SConscript('IMP/SConscript')
