Import('env')

files = [
    'constants.h',
    'Decorator.h',
    'DerivativeAccumulator.h',
    'Key.h',
    'Model.h',
    'Object.h',
    'Optimizer.h',
    'OptimizerState.h',
    'PairContainer.h',
    'PairModifier.h',
    'PairScore.h',
    'Particle.h',
    'Refiner.h',
    'Pointer.h',
    'RefCounted.h',
    'Restraint.h',
    'ScoreState.h',
    'SingletonContainer.h',
    'SingletonModifier.h',
    'SingletonScore.h',
    'stream.h',
    'TripletScore.h',
    'UnaryFunction.h',
    'VersionInfo.h',
    'WeakPointer.h',
    'base_types.h',
    'config.h',
    'container_macros.h',
    'deprecation.h',
    'exception.h',
    'log.h',
    'macros.h',
    'random.h',
    'utility.h',
    ]

# Subdirectories
files = [File(f) for f in files] \
        + SConscript('internal/SConscript')

# Install the include files:
includedir = env['includedir']
inst = env.InstallHierarchy(includedir, 'IMP',
                            'IMP, an Integrative Modeling Platform.', files)
env.Alias('kernel-install', inst)
env.Alias('install', inst)
