Import('env')

# Subdirectories
files = SConscript('IMP/SConscript')

# Install the include files:
includedir = env['includedir']
inst = env.InstallHierarchy(includedir, 'IMP',
                            'IMP, an Integrative Modeling Platform.', files)
env.Alias('install', inst)
