Import('env')
import scons_tools.data

files=env.IMPModuleGetSources()

if "ProtoBuf" in scons_tools.data.get(env).modules['RMF'].dependencies:
    files.append(File("#/build/src/RMF.pb.cpp"))

# Build and install the shared library:
env.IMPModuleLib(files=files)
