files = [
         'bounding_sphere.cpp',
         'knn.cpp',
         'polygons.cpp',
         'polyhedrons.cpp',
         'sphere_cover.cpp',
         'union_of_balls.cpp',
        ]

files = [File(x) for x in files]
Return('files')
