Import('env')
file_list = ['nup84_complex_in_bead_representation.py',
             'basic_setup.py',
             'rigid_body_and_excluded_volume_restraint.py',
             'em_restraint.py',
             'saxs_restraint.py',
             'basic_display.py',
             'nup84_complex_in_bead_representation.readme',
             'basic_setup.readme',
             'rigid_body_and_excluded_volume_restraint.readme',
             'em_restraint.readme',
             'saxs_restraint.readme',
             'basic_display.readme']
env.IMPModuleExamples(example_files=file_list,
                      data_files=env.IMPModuleGetExampleData())
