Import('env')
file_list = ['basic_setup.py',
             'rigid_body_and_excluded_volume_restraint.py',
             'em_restraint.py',
             'basic_setup.readme',
             'rigid_body_and_excluded_volume_restraint.readme',
             'em_restraint.readme']
env.IMPModuleExamples(example_files=file_list,
                      data_files=env.IMPModuleGetExampleData())
