import os.path
Import('env')

files = ['DistanceToSingletonScore.h']

# Install the include files:
includedir = os.path.join(env['includedir'], 'IMP', 'singleton_scores')
inst = env.Install(includedir, files)
env.Alias('install', inst)
