Import('env')
files = [
      'density_analysis.h',
#         'FFTFitting.h',
         'weighted_excluded_volume.h',
         'sampling_space.h',
         'FittingSolutionRecord.h',
         'SingleDominoRun.h',
         'm_rigid_fitting.h',
         'fitting_solutions_reader_writer.h',
         'fitting_tools.h',
         'SettingsData.h',
         'DataContainer.h',
         'restraints_utils.h',
         'sampling_space_utils.h',
         'WeightedExcludedVolumeRestraint.h',
#         'mc_cg_refinement.h'
        ]
# Install the include files:
env.IMPModuleInclude(files)
