Import('env')
files = [
         'DataPoints.h',
         'DataPointsAssignment.h',
         'ClusteringEngine.h',
         'VQClustering.h',
         'density_analysis.h',
         'fft_based_rigid_fitting.h',
         'MolCnSymmAxisDetector.h',
         'weighted_excluded_volume.h',
                 'WeightedExcludedVolumeRestraint3.h',
         'FittingSolutionRecord.h',
         'pca_based_rigid_fitting.h',
         'fitting_solutions_reader_writer.h',
         'fitting_tools.h',
         'SettingsData.h',
         'WeightedExcludedVolumeRestraint.h',
         'anchor_graph.h',
         'RMSDClustering.h',
         'fitting_clustering.h',
        'GeometricHash.h',
        'TransformationClustering.h',
        'proteomics_reader.h',
        'anchors_reader.h',
        'coarse_molecule.h',
        'fitting_utils.h',
        'RadiusOfGyrationRestraint.h',
        'anchor_utilities.h'
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPModuleInclude(files)
