Import('env')

env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 authors=["Keren Lasker", "Javier Velazquez-Muriel", "Friedrich Foerster"],
                 brief="This module allows density maps to be used to generate restraints.",
                 overview="This module provides basic utilities for handling 2D and 3D density maps. The main functionalities are: (1) Reading and writing various density map formts such as XPLOR, MRC, EM and SPIDER.\n(2) Simulating density maps of particles, supports particles of any radiuii and mass.\n(3) Calculating cross-correlation scores bewteen a density map and a set of particles.",
                 publications=env.IMPStandardPublications(),
                 license=env.IMPStandardLicense())
