Import('env')

env.IMPModuleAbout(author="Someone", version="SVN", description="A private module")

# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Append(LIBS=env['CGAL_LIBS'])

env.Append(LIBS=['imp_core', 'imp_atom', 'imp_algebra'])
env.validate()

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
SConscript('bin/SConscript', exports='env')
