Import('env')


env.IMPModuleBuild(author="Daniel Russel", version="SVN",
                   description="High level helper functions built on other modules.",
                   required_modules=['atom', 'core', 'algebra'],
                   optional_dependencies=['CGAL'])
