/**
 *  \file ListGroupnameContainer.cpp   \brief A list of Classnames.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 IMP Inventors. All rights reserved.
 *
 */

#include <IMP/core/internal/groupname_helpers.h>
#include <IMP/GroupnameModifier.h>
#include <IMP/GroupnameScore.h>

IMPCORE_BEGIN_INTERNAL_NAMESPACE

unsigned int ListLikeGroupnameContainer
::get_number_of_classnames() const {
  IMP_CHECK_OBJECT(this);
  IMP_USAGE_CHECK(get_is_up_to_date(),
                  "Attempting to use container "
                  << get_name() << " that is not up to date."
                  << " Call Model::evaluate() first, or something is broken.");
  return data_.size();
}
bool ListLikeGroupnameContainer
::get_contains_classname(PassValue vt) const {
  IMP_CHECK_OBJECT(this);
  return std::binary_search(data_.begin(), data_.end(), vt);
}

Value ListLikeGroupnameContainer
::get_classname(unsigned int i) const {
  IMP_CHECK_OBJECT(this);
  return data_[i];
}

void ListLikeGroupnameContainer
::do_show(std::ostream &out) const {
  out << "contains " << data_.size() << std::endl;
}


ParticlesTemp ListLikeGroupnameContainer
::get_contained_particles() const {
  return IMP::internal::flatten(data_);
}

bool ListLikeGroupnameContainer
::get_contained_particles_changed() const {
  return !get_added()->data_.empty() || !get_removed()->data_.empty();
}

GroupnameContainerPair ListLikeGroupnameContainer
::get_added_and_removed_containers() const {
  return GroupnameContainerPair(new ListLikeGroupnameContainer(),
                                new ListLikeGroupnameContainer());
}

IMPCORE_END_INTERNAL_NAMESPACE
