Import('env')
import scons_tools.examples

env= env.IMPSystem(
                   required_modules=['core', 'atom', 'rmf'],
                   last_imp_version="""core SVN 7432M with CGAL
atom SVN 7432M with CGAL, Boost.FileSystem
container SVN 7432
kernel SVN 7432 with Boost.FileSystem, NetCDF
cgal SVN 7432""",
                   # this is true if the scripts can be run incompletely as test cases
                   # eg if it works to do "sample_0.py 1 1000" and then "analyze_0.py"
                   # without doing all of the sampling required. This can be implementedf
                   # either by providing intermediate data or by only analyzing the data
                   # that happens to be there
                   testable=True, parallelizable=True)
if env:
    files= ["setup",
            "sample_0",
            "analyze_0"]
    scons_tools.examples.add_python_example(env, "setup.py",
                                            "setup.readme")
    scons_tools.examples.add_python_example(env, "sample_0.py",
                                            "sample_0.readme")
    scons_tools.examples.add_python_example(env, "analyze_0.py",
                                            "analyze_0.readme")
