/**
 *  \file FilteredListSingletonContainer.cpp
 *  \brief Simple xyzr decorator.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/FilteredListSingletonContainer.h"
#include <algorithm>


IMPCORE_BEGIN_NAMESPACE

namespace {

  class Found {
    typedef FilteredListSingletonContainer
    ::SingletonFilterConstIterator It;
    It b_,e_;
  public:
    Found(It b,
          It e):
      b_(b), e_(e){}
    bool operator()(Particle* vt) const {
      for (It c=b_; c != e_; ++c) {
        if ((*c)->get_contains_particle(vt)) return true;
      }
      return false;
    }
  };

}

FilteredListSingletonContainer
::FilteredListSingletonContainer(): sorted_(true){
}

void FilteredListSingletonContainer::add_particle(Particle* vt) {
  IMP_CHECK_OBJECT(this);
  // For VC which can't convert the iterators
  const FilteredListSingletonContainer *cthis=
    const_cast<const FilteredListSingletonContainer*>(this);
  if (!Found(cthis->singleton_filters_begin(),
             cthis->singleton_filters_end())(vt)) {
    data_.push_back(vt);
    if (sorted_) {
      std::sort(data_.begin(), data_.end());
    }
  }
}

bool
FilteredListSingletonContainer
::get_contains_particle(Particle* vt) const {
  IMP_check(sorted_, "Cannot check if the container contains an object "
            << "while you are editing it.", InvalidStateException);
  return std::binary_search(particles_begin(),
                            particles_end(), vt);
}

void FilteredListSingletonContainer::show(std::ostream &out) const {
  IMP_CHECK_OBJECT(this);
  out << "FilteredListSingletonContainer with "
      << get_number_of_particles()
      << " particles." << std::endl;
}


void FilteredListSingletonContainer::set_is_editing(bool tf) {
  if (tf== !sorted_) return;
  else {
    sorted_=!tf;
    if (sorted_) {
      std::sort(data_.begin(), data_.end());
    }
  }
}

unsigned int
FilteredListSingletonContainer::get_number_of_particles() const {
  return data_.size();
}

Particle*
FilteredListSingletonContainer::get_particle(unsigned int i) const {
  IMP_check(i < get_number_of_particles(),
            "Out of range " << i << " for array of size " << data_.size(),
            IndexException);
  return data_[i];
}



IMP_LIST_IMPL(FilteredListSingletonContainer,
              SingletonFilter,
              singleton_filter,
              SingletonContainer*,
              SingletonContainers,,,)

IMPCORE_END_NAMESPACE
