/**
 *  \file PairsScoreState.cpp
 *  \brief Use a PairModifier applied to a PairContainer to
 *  maintain an invariant
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/PairsScoreState.h"
#include "IMP/core/internal/container_helpers.h"

IMPCORE_BEGIN_NAMESPACE

PairsScoreState::PairsScoreState(PairModifier *f,
                                           PairContainer *c):
  f_(f), c_(c){
}

PairsScoreState::~PairsScoreState(){}


void PairsScoreState::do_before_evaluate()
{
  IMP_LOG(TERSE, "Begin PairsScoreState::evaluate" << std::endl);
  IMP_CHECK_OBJECT(f_);
  IMP_CHECK_OBJECT(c_);
  for (PairContainer::ParticlePairIterator
       it= c_->particle_pairs_begin();
       it != c_->particle_pairs_end(); ++it) {
    IMP_LOG(VERBOSE, "Applying"<< std::endl);

    // Need the .get for template matching
    internal::ContainerTraits<ParticlePair>::apply(f_.get(), *it);
  }
  IMP_LOG(TERSE, "End PairsScoreState::evaluate" << std::endl);
}


void PairsScoreState::show(std::ostream &out) const {
  out << "PairsScoreState base" << std::endl;
}

IMPCORE_END_NAMESPACE
