/**
 *  \file ParticlePairContainer.cpp   \brief Container for particle_pair.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-8 Sali Lab. All rights reserved.
 *
 */

#include "IMP/core/ParticlePairContainer.h"


IMPCORE_BEGIN_NAMESPACE

ParticlePairContainer::ParticlePairContainer(){}

ParticlePairContainer::~ParticlePairContainer(){}

void ParticlePairContainer::show(std::ostream &out) const {
  out << "ParticlePairContainer" << std::endl;
}


IMPCORE_END_NAMESPACE
