Import('env')

env= env.IMPApplication(required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="rg", source=["rg.cpp"])
    env.IMPCPPExecutable(target="validate_profile", source=["validate_profile.cpp"])
    env.IMPCPPExecutable(target="compute_chi", source=["compute_chi.cpp"])
