Import('env')

env= env.IMPApplication(name="saxs_tools", version="SVN",
                        authors=["Dina Schneidman"],
                        brief="Tools for SAXS",
                        overview="",
                        license=env.IMPStandardLicense(),
                        publications=[],
                        required_modules=['saxs'],
                        required_dependencies=['Boost.ProgramOptions'],
                        python=False)

if env:
    env.IMPCPPExecutable(target="rg", source=["rg.cpp"])
    env.IMPCPPExecutable(target="validate_profile", source=["validate_profile.cpp"])
