files = [
         'inference_utility.h',
         'loopy_inference.h',
         'maximal_cliques.h',
         'restraint_evaluator.h',
         'tree_inference.h',
        ]

files = [File(x) for x in files]
Return('files')
