#!/usr/bin/python
import sys
import os
import os.path
header_template="""/**
 *  \\file fname.h
 *  \\brief description
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 */

#ifndef IMPMODULE_FNAME_H
#define IMPMODULE_FNAME_H

#include "module_config.h"

IMPMODULE_BEGIN_NAMESPACE


IMPMODULE_END_NAMESPACE

#endif  /* IMPMODULE_FNAME_H */
"""

cpp_template="""/**
 *  \\file fname.cpp
 *  \\brief description.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 *
 */

#include <IMP/module/fname.h>

IMPMODULE_BEGIN_NAMESPACE

IMPMODULE_END_NAMESPACE
"""

def fixup(module, name, descr, text):
    return text.replace("fname", name)\
        .replace("FNAME", name.upper())\
        .replace("MODULE", module.upper())\
        .replace("module", module)

def main():
    if len(sys.argv) != 4:
        print "usage: "+sys.argv[0] + " dir name description"
        sys.exit(1)
    module=os.path.split(sys.argv[1])[-1]
    name= sys.argv[2]
    descr= sys.argv[3]
    h= fixup(module, name, descr, header_template)
    cpp= fixup(module, name, descr, cpp_template)
    open(os.path.join(sys.argv[1], "include", name+".h"), "w").write(h)
    open(os.path.join(sys.argv[1], "src", name+".cpp"), "w").write(cpp)
if __name__ == '__main__':
    main()
