#!/usr/bin/python

import os
import os.path
import sys
import subprocess

def main():
    if len(sys.argv) != 2:
        print("""Usage: %s build_directory
This script will setup up the named directory for IMP out-of-source builds.
The IMP source is found in the same location as this script.""" \
% sys.argv[0])
        return
    script = os.path.abspath(sys.argv[0])
    imppath= os.path.split(os.path.split(script)[0])[0]
    try:
        relimppath= os.path.relpath(imppath, os.path.abspath(sys.argv[1]))
    except AttributeError:
        print "Platform does not support os.path.relpath, links will be made using absolute paths. Sorry. You can replace the SConstruct and scons_tools links and the repository line in the config.py with relative paths by hand."
        relimppath= os.path.abspath(sys.argv[1])
    path_to_build= sys.argv[1]
    print "IMP source found at ", imppath
    print "Setting up IMP build directory at ", path_to_build
    if os.path.isfile(os.path.join(path_to_build, "SConstruct")):
        print "SConstruct file already exists in this directory."
        return
    print "path to imp is", relimppath
    print "path to build is", path_to_build
    os.symlink(os.path.join(relimppath, "SConstruct"),
               os.path.join(path_to_build, "SConstruct"))
    os.symlink(os.path.join(relimppath, "scons_tools"),
               os.path.join(path_to_build,  "scons_tools"))
    config="repository=\"%s\"\n" % relimppath
    open(os.path.join(path_to_build,"config.py"), "w").write(config)
    oldconfig="cxxcompiler='/dev/null'\n"
    cmd="cd "+imppath+"; scons -c >& /dev/null"
    print "Cleaning up source directory:", cmd
    sp=subprocess.Popen([cmd], shell=True, stderr=subprocess.STDOUT)
    ret=sp.wait()
    open(os.path.join(imppath, "config.py"), "w").write(oldconfig)

if __name__ == '__main__':
    main()
