#!/bin/sh
cpp=`find * -name \*.h -or -name \*.cpp`
py=`find * -name \*.py`
dox=`find * -name \*.dox`

echo $cpp
echo $py
echo $dox

sed -i.old 's#::create(#::setup_particle(#g' $cpp $dox
sed -i.old 's#\.create(#.setup_particle(#g' $py $dox
sed -i.old 's#::cast(#::decorate_particle(#g' $cpp $dox
sed -i.old 's#\.cast(#.decorate_particle(#g' $py $dox
sed -i.old 's# create(# setup_particle(#g' $cpp $dox
sed -i.old 's# is_instance_of(# particle_is_instance(#g' $cpp $dox $py
sed -i.old 's#(is_instance_of(#(particle_is_instance(#g' $cpp $dox $py
sed -i.old 's#!is_instance_of(#!particle_is_instance(#g' $cpp $dox $py
sed -i.old 's#\.is_instance_of(#.particle_is_instance(#g' $cpp $dox $py
sed -i.old 's#::is_instance_of(#::particle_is_instance(#g' $cpp $dox $py
sed -i.old 's#FitRestraint.decorate_particle(#FitRestraint.cast(#g' $py
