Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'FormFactorTable.cpp',
         'RadialDistributionFunction.cpp',
         'SAXSProfile.cpp',
         'SaxsData.cpp',
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
