Import('env')
files = [
         'DerivativeCalculator.cpp',
         'Distribution.cpp',
         'FormFactorTable.cpp',
         'Profile.cpp',
         'Restraint.cpp',
         'RadiusOfGyrationRestraint.cpp',
         'Score.cpp',
         'SolventAccessibleSurface.cpp'
        ]

# Build and install the shared library:
env.IMPModuleLib(files)
