Import('env')
e = env.IMPSharedLibraryEnvironment()

files = [
         'SAXSProfile.cpp', 'FormFactorTable.cpp', 'RadialDistributionFunction.cpp'
        ]

# Build and install the shared library:
e.IMPSharedLibrary(files, install=True)
