/**
 *  \file ListTripletContainer.h    \brief Store a list of ParticleTripletsTemp
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 */

#ifndef IMPKERNEL_INTERNAL_INTERNAL_LIST_TRIPLET_CONTAINER_H
#define IMPKERNEL_INTERNAL_INTERNAL_LIST_TRIPLET_CONTAINER_H

#include "../kernel_config.h"
#include "container_helpers.h"
#include "ListLikeTripletContainer.h"

IMP_BEGIN_INTERNAL_NAMESPACE


class IMPEXPORT InternalListTripletContainer:
  public ListLikeTripletContainer
{
  IMP_ACTIVE_CONTAINER_DECL(InternalListTripletContainer);
 public:
  InternalListTripletContainer(Model *m, std::string name);
  InternalListTripletContainer(Model *m, const char *name);
  void add_particle_triplet(const ParticleTriplet& vt) {
    IMP_USAGE_CHECK(IMP::internal::is_valid(vt),
                    "Passed Triplet cannot be nullptr (or None)");
    add_to_list(IMP::internal::get_index(vt));
  }
  void add_particle_triplet(const ParticleIndexTriplet& vt) {
    add_to_list(vt);
  }
  void add_particle_triplets(const ParticleTripletsTemp &c) {
    if (c.empty()) return;
    ParticleIndexTriplets cp= IMP::internal::get_index(c);
    add_to_list(cp);
  }
  void remove_particle_triplets(const ParticleTripletsTemp &c);
  void set_particle_triplets(ParticleTripletsTemp c) {
    ParticleIndexTriplets cp= IMP::internal::get_index(c);
    update_list(cp);
  }
  void set_particle_triplets(ParticleIndexTriplets cp) {
    update_list(cp);
  }
  void clear_particle_triplets() {
    ParticleIndexTriplets t;
    update_list(t);
  }
  bool get_is_up_to_date() const {
    return true;
  }
  IMP_LISTLIKE_TRIPLET_CONTAINER(InternalListTripletContainer);
};

IMP_OBJECTS(InternalListTripletContainer, InternalListTripletContainers);

IMP_END_INTERNAL_NAMESPACE

#endif  /* IMPKERNEL_INTERNAL_INTERNAL_LIST_TRIPLET_CONTAINER_H */
