/**
 *  \file internal/particle_helpers.h
 *  \brief A container for Singletons.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2011 IMP Inventors. All rights reserved.
 */

#ifndef IMPKERNEL_INTERNAL_SINGLETON_HELPERS_H
#define IMPKERNEL_INTERNAL_SINGLETON_HELPERS_H

#include "../kernel_config.h"
#include "../SingletonContainer.h"
#include "../SingletonModifier.h"
#include "../SingletonScore.h"
#include "container_helpers.h"
#include <algorithm>

IMP_BEGIN_INTERNAL_NAMESPACE
template <class Score>
struct SimpleRestraintParentTraits<Score,
       typename boost::enable_if<
         boost::is_base_of<SingletonScore, Score> >::type> {
  typedef IMP::SingletonScoreRestraint SimpleRestraint;
  typedef IMP::SingletonsScoreRestraint SimplesRestraint;
};
IMP_END_INTERNAL_NAMESPACE


#endif  /* IMPKERNEL_INTERNAL_SINGLETON_HELPERS_H */
