/**
 *  \file internal/particle_triplet_helpers.h
 *  \brief A container for Triplets.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2012 IMP Inventors. All rights reserved.
 */

#ifndef IMPKERNEL_INTERNAL_TRIPLET_HELPERS_H
#define IMPKERNEL_INTERNAL_TRIPLET_HELPERS_H

#include "../kernel_config.h"
#include "../TripletContainer.h"
#include "../TripletModifier.h"
#include "../TripletDerivativeModifier.h"
#include "../TripletScore.h"
#include "../declare_Model.h"
#include "container_helpers.h"
#include <algorithm>

IMP_BEGIN_INTERNAL_NAMESPACE
template <class Score>
struct SimpleRestraintParentTraits<Score,
       typename boost::enable_if<
         boost::is_base_of<TripletScore, Score> >::type> {
  typedef IMP::TripletScoreRestraint SimpleRestraint;
  typedef IMP::TripletsScoreRestraint SimplesRestraint;
};

template <class S>
inline double call_evaluate_index(Model *m, const S *s,
                           const ParticleIndexTriplet& a,
                           DerivativeAccumulator *da) {
  return s->S::evaluate_index(m, a, da);
}
inline double call_evaluate_index(Model *m, const TripletScore *s,
                           const ParticleIndexTriplet& a,
                           DerivativeAccumulator *da) {
    return s->evaluate_index(m, a, da);
}
template <class S>
inline double call_evaluate_if_good_index(Model *m, const S *s,
                                   const ParticleIndexTriplet& a,
                                   DerivativeAccumulator *da,
                                   double max) {
  return s->S::evaluate_if_good_index(m, a, da, max);
}
inline double call_evaluate_if_good_index(Model *m, const TripletScore *s,
                                   const ParticleIndexTriplet& a,
                                   DerivativeAccumulator *da,
                                   double max) {
  return s->evaluate_if_good_index(m, a, da, max);
}
template <class S>
inline void call_apply_index(Model *m, const S *s,
                      const ParticleIndexTriplet& a) {
  s->S::apply_index(m, a);
}
inline void call_apply(Model *m, const TripletModifier *s,
                const ParticleIndexTriplet& a) {
  s->apply_index(m, a);
}
template <class S>
inline void call_apply_index(Model *m, const S *s,
                      const ParticleIndexTriplet& a,
                      DerivativeAccumulator *&da) {
  s->S::apply_index(m, a, da);
}
inline void call_apply_index(Model *m, const TripletDerivativeModifier *s,
                      const ParticleIndexTriplet& a,
                  DerivativeAccumulator &da) {
  s->apply_index(m, a, da);
}

IMP_END_INTERNAL_NAMESPACE


#endif  /* IMPKERNEL_INTERNAL_TRIPLET_HELPERS_H */
