Import('env')
Export('env')

env.IMPModuleAbout(author="Someone", version="SVN", description="A private module")

env.Append(LIBS=['imp_core'])
env.validate()

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
SConscript('bin/SConscript')
