Import('env')

env.IMPModuleAbout(author='IMP developers', version='SVN',
                   description='General purpose features of broad utility.')

# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Prepend(LIBS=env['CGAL_LIBS'])

# No dependent libraries, so this module can always be built:
env.validate()

env.Prepend(LIBS=['imp_algebra'])

# Subdirectories:
SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env')
SConscript('pyext/SConscript', exports='env')
SConscript('test/SConscript', exports='env')
