files = [
         'inference_utility.cpp',
         'loopy_inference.cpp',
         'restraint_evaluator.cpp',
         'tree_inference.cpp',
        ]

files = [File(x) for x in files]
Return('files')
