Import('env')


# Link against CGAL if present:
if env['CGAL_LIBS']:
    env.Append(LIBS=env['CGAL_LIBS'])

env.IMPModuleBuild(author='Daniel Russel', version='SVN',
                   description='Build search structures over particles.')
