Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost

scons_tools.dependency.boost.configure_tr1_check(env)
deplist=[]

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem",
                                               'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p;",
                                               extra_boost_libs=["system"])
deplist.append('Boost.FileSystem')




env.IMPModuleBuild(version='nightly-14/3/2012',
                   module='kernel', module_libname="imp",
                   module_pylibname="_IMP", module_include_path="IMP",
                   module_preproc="IMP",
                   module_namespace="IMP",
                   required_modules=['algebra', 'base'],
                   lib_only_required_modules=['compatibility'],
                   required_dependencies=['Boost'],
                   optional_dependencies=deplist)

# Document the IMP.test Python module
env.Append(IMP_PYTHON_DOCS=['test'])

# Make sure coverage.py is available outside of the IMP package for tests
env.InstallAs('#/build/lib/imp_coverage.py',
              'pyext/src/test/_compat_python/coverage.py')
