Import('env')
import scons_tools.dependency
import scons_tools.dependency.boost

deplist=[]

scons_tools.dependency.boost.add_boost_library(env, "FileSystem", "filesystem",
                                               'boost/filesystem/path.hpp',
                                               body="boost::filesystem::path p; boost::system::get_system_category();",
                                               extra_boost_libs=["system"])
deplist.append('Boost.FileSystem')




env.IMPModuleBuild(module='kernel', module_libname="imp",
                   module_pylibname="_IMP", module_include_path="IMP",
                   module_preproc="IMP",
                   module_namespace="IMP")

# Document the IMP.test Python module
env.Append(IMP_PYTHON_DOCS=['test'])
