/**
 *  \file PairScore.cpp  \brief Define PairScore
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2011 IMP Inventors. All rights reserved.
 */

#include <IMP/PairScore.h>
#include <IMP/internal/utility.h>
#include <IMP/Restraint.h>
#include <IMP/macros.h>
#include <IMP/PairScore.h>
#include <IMP/internal/container_helpers.h>
IMP_BEGIN_NAMESPACE

PairScore::PairScore(std::string name):
  Object(name)
{
  /* Implemented here rather than in the header so that PairScore
     symbols are present in the kernel DSO */
}

PairScoreRestraint::PairScoreRestraint(std::string name):
  Restraint(name){}

PairsScoreRestraint::PairsScoreRestraint(std::string name):
  Restraint(name){}


namespace {


  class PairRestraint :
    public PairScoreRestraint
  {
    IMP::OwnerPointer<PairScore> ss_;
    ParticlePair v_;
  public:
    //! Create the restraint.
    /** This function takes the function to apply to the
        stored Pair and the Pair.
    */
    PairRestraint(PairScore *ss,
                       const ParticlePair& vt,
                       std::string name);

    PairScore* get_score() const {
      return ss_;
    }
    ParticlePair get_argument() const {
      return v_;
    }

    IMP_RESTRAINT(PairRestraint);
  };

  PairRestraint
  ::PairRestraint(PairScore *ss,
                       const ParticlePair& vt,
                       std::string name):
    PairScoreRestraint(name),
    ss_(ss),
    v_(vt)
  {
  }

  double PairRestraint
  ::unprotected_evaluate(DerivativeAccumulator *accum) const
  {
    IMP_OBJECT_LOG;
    IMP_CHECK_OBJECT(ss_);
    return ss_->evaluate(v_, accum);
  }

  ParticlesTemp PairRestraint::get_input_particles() const
  {
    return IMP::internal::get_input_particles(ss_.get(), v_);
  }

  ContainersTemp PairRestraint::get_input_containers() const
  {
    return IMP::internal::get_input_containers(ss_.get(), v_);
  }

  void PairRestraint::do_show(std::ostream& out) const
  {
    out << "score " << ss_->get_name() << std::endl;
    out << "data " << IMP::internal::streamable(v_) << std::endl;
  }
}


Restraints
PairScore
::get_current_decomposition(const ParticlePair& vt) const {
  return Restraints(1,
                    new PairRestraint(const_cast<PairScore*>(this),
                                           vt,
                                           get_name()));
}

IMP_END_NAMESPACE
