/**
 *  \file PairFilter.cpp   \brief Filter for particle_pair.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 *
 */

#include "IMP/PairFilter.h"
#include "IMP/internal/utility.h"
#include "IMP/PairModifier.h"

IMP_BEGIN_NAMESPACE

namespace {
  unsigned int next_index=0;
}


PairFilter::PairFilter(std::string name) {
  set_name(internal::make_object_name(name, next_index++));
}

IMP_END_NAMESPACE
