/**
 *  \file QuadFilter.cpp   \brief Filter for particle_quad.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 Sali Lab. All rights reserved.
 *
 */

#include "IMP/QuadFilter.h"
#include "IMP/internal/utility.h"
#include "IMP/QuadModifier.h"

IMP_BEGIN_NAMESPACE

namespace {
  unsigned int next_index=0;
}


QuadFilter::QuadFilter(std::string name) {
  set_name(internal::make_object_name(name, next_index++));
}

IMP_END_NAMESPACE
