/**
 *  \file QuadScore.cpp  \brief Define QuadScore
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 IMP Inventors. All rights reserved.
 */

#include <IMP/QuadScore.h>
#include <IMP/internal/utility.h>

IMP_BEGIN_NAMESPACE

QuadScore::QuadScore(std::string name):
  Object(name)
{
  /* Implemented here rather than in the header so that PairScore
     symbols are present in the kernel DSO */
}

IMP_END_NAMESPACE
