Import('env')

files = [
         'FailureHandler.cpp',
         'Key.cpp',
         'Model.cpp',
         'Object.cpp',
         'Optimizer.cpp',
         'OptimizerState.cpp',
         'PairContainer.cpp',
         'PairFilter.cpp',
         'PairModifier.cpp',
         'PairScore.cpp',
         'Particle.cpp',
         'Refiner.cpp',
         'Restraint.cpp',
         'ScoreState.cpp',
         'SingletonContainer.cpp',
         'SingletonFilter.cpp',
         'SingletonModifier.cpp',
         'SingletonScore.cpp',
         'TripletScore.cpp',
         'UnaryFunction.cpp',
         'base_types.cpp',
         'directories.cpp',
         'exception.cpp',
         'log.cpp',
         'random.cpp',
         'utility.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
env.IMPModuleLib(files)
