/**
 *  \file SingletonContainer.cpp   \brief Container for particle.
 *
 *  This file is generated by a script (core/tools/make-container).
 *  Do not edit directly.
 *
 *  Copyright 2007-9 Sali Lab. All rights reserved.
 *
 */

#include "IMP/SingletonContainer.h"


IMP_BEGIN_NAMESPACE

SingletonContainer::SingletonContainer(){}


IMP_END_NAMESPACE
