/**
 *  \file SingletonFilter.cpp   \brief Filter for particle.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 IMP Inventors. All rights reserved.
 *
 */

#include "IMP/SingletonFilter.h"
#include "IMP/internal/utility.h"
#include "IMP/SingletonModifier.h"

IMP_BEGIN_NAMESPACE

SingletonFilter::SingletonFilter(std::string name): Object(name) {
}

IMP_END_NAMESPACE
