/**
 *  \file TripletFilter.cpp   \brief Filter for triplet.
 *
 *  This file is generated by a script (core/tools/make-filter).
 *  Do not edit directly.
 *
 *  Copyright 2007-2010 IMP Inventors. All rights reserved.
 *
 */

#include "IMP/TripletFilter.h"
#include "IMP/internal/utility.h"
#include "IMP/TripletModifier.h"
#include <algorithm>

IMP_BEGIN_NAMESPACE

TripletFilter::TripletFilter(std::string name): Object(name) {
}
namespace {
struct GCP {
  const TripletFilter *back_;
  GCP(const TripletFilter *n): back_(n){}
  template <class T>
  bool operator()(const T &p) const {
    return back_->get_contains_particle_triplet(p);
  }
};
}
void TripletFilter
::filter_in_place(ParticleTripletsTemp &ps) const {
  ps.erase(std::remove_if(ps.begin(), ps.end(),
                          GCP(this)),
           ps.end());

}

IMP_END_NAMESPACE
