Import('env')

# All .dox, .pdf and .pdb files are installed
env.IMPModuleDoc(env.IMPModuleGetDocs(),
                 # A python list of the author names
                 authors=["J. Velazquez-Muriel","D. Russel"],
                 # Provide a brief description of what the module does
                 brief="This module provides functionality to use two-dimensional EM images as restraints",
                 # Provide a longer description of what the module does
                 # This description can have multiple paragraphs and all sorts of markup
                 overview= \
                 """
                    This module allows to use restraints coming from EM class averages.
                    The main class is EM2DRestraint, that you can add to any of your models. This class in turn uses internally the Fine2DRegistraitionRestraint.
                    Don't use the later one directly. Another interesting class is RegistrationResult,
                    that stores all the information obtained after matching a projection with the EM image.
                    And of course Image, which manages the EM images. Finally, we provide a number of
                    routines for image processing, like alignment, filtering or morphological operations.

                    The module goes together with the EModel2D application, that uses the EM2DRestraint for
                    modeling of macromolecular assemblies using class averages. The alogirthm is described
                    in the paper:

                    xxx (Not yet) xxx

                    As a side note, the class Image has a header that is specific for EM images, but if you
                    don't care for that information, you can use the class to deal with any sort of
                    image, not only EM.

                    The module works with OpenCV 2.1, 2.2 and 2.3. We haven't tried with newer versions yet.
                 """,
                 # IMPPublications can be added using the env.IMPPublication() function
                 # The result should be a python list
                 # env.IMPStandardPublications() defines the general IMP publications
                 publications=env.IMPStandardPublications()\
                     + [env.IMPPublication(authors=["Some Person", "Someone Else"],
                                        title="A silly title of no paper",
                                        journal="Dev Null", year=2051),
                        env.IMPWebsite(url="http://www.salilab.org/imp", name="IMP")],
                 # License can be either env.IMPStandardLicense() to be the same as the rest of IMP
                 # or it can be a string describing the license, such as "GPL".
                 license=env.IMPStandardLicense())
