Import('env')

env.IMPModuleBuild(version='nightly-12',
                   required_modules=['display', 'algebra'],
                   optional_modules=['RMF'],
                   lib_only_required_modules=['statistics', 'core', 'container'])
