Import('env')
Export('env')

env.IMPModuleAbout(author='Keren Lasker', version='SVN',
                   description='DOMINO optimizer.')

# No dependent libraries, so this module can always be built:
env.validate()

env.Append(LIBS=['imp_core', 'imp_algebra', 'imp_atom'])

# Subdirectories:
SConscript('src/SConscript')
SConscript('include/SConscript')
SConscript('pyext/SConscript')
SConscript('test/SConscript')
