Import('env')

files = ['NonbondedListScoreState.cpp', 'BipartiteNonbondedListScoreState.cpp']

bonded_lists_files = SConscript('bonded_lists/SConscript')

files = [File(x) for x in files] + bonded_lists_files
Return('files')
