Import('env')

files = ['NonbondedListScoreState.cpp',
         'MaxChangeScoreState.cpp', 'BondDecoratorListScoreState.cpp',
         'AllNonbondedListScoreState.cpp',
         'BipartiteNonbondedListScoreState.cpp',
         'GravityCenterScoreState.cpp']

files = [File(x) for x in files]
Return('files')
