Import('env')
import scons_tools.checks

scons_tools.checks.add_external_library(env, "OpenMM", "OpenMM",
                                       "OpenMM.h", extra_libs=[])


# See IMP.gsl for an example of how to add external dependencies to a module
env.IMPModuleBuild(version='SVN',
                   # The required modules are the other IMP modules that must be built to use this one
                   required_modules=['container', 'atom'],
                   # the optional dependencies are external libraries that are needed
                   required_dependencies=["OpenMM"])
