import os.path
Import('env')

files = ['BallMover.h', 'NormalMover.h']

includedir = os.path.join(env['includedir'], 'IMP', 'optimizers', 'movers' )
inst = env.Install(includedir, files)
env.Alias('install', inst)
