import os.path
Import('env')

files = ['BallMover.h', 'NormalMover.h']

# Place in build directory:
env.Install('#/build/include/IMP/optimizers/movers', files)

includedir = os.path.join(env['includedir'], 'IMP', 'optimizers', 'movers' )
inst = env.Install(includedir, files)
env.Alias('install', inst)
