Import('env')
import scons_tools.dependency

scons_tools.dependency.add_external_library(env,
    "eigen3", None,
    "Eigen/Eigen")

scons_tools.dependency.add_external_library(env,
    "CHOLMOD", ['cholmod','amd','metis','colamd','ccolamd','camd','blas'],
    "ufsparse/cholmod.h")


env.IMPModuleBuild(version='1',
       required_modules=['kernel', 'container', 'core', 'atom', 'em',
       'statistics', 'saxs'],
       required_dependencies=['eigen3'],
       optional_dependencies=['CHOLMOD'])
