Import('env')
import scons_tools.dependency 

scons_tools.dependency.add_external_library(env,
    "eigen3", ['m'],
    "eigen3/Eigen/Eigen")


env.IMPModuleBuild(version='SVN',
       required_modules=['kernel', 'container', 'core', 'atom', 'em',
       'statistics', 'saxs'], 
       required_dependencies=['eigen3'])
