Import('env')

files = [
         'BranchAndBoundSampler.cpp',
         'DiscreteSampler.cpp',
         'DominoSampler.cpp',
         'Subset.cpp',
         'particle_states.cpp',
         'subset_evaluators.cpp',
         'subset_filters.cpp',
         'subset_states.cpp',
         'utility.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
env.IMPModuleLib(files)
