Import('env')

files = [
         'BildWriter.cpp',
         'CMMWriter.cpp',
         'ChimeraWriter.cpp',
         'Color.cpp',
         'Colored.cpp',
         'FilterGeometry.cpp',
         'GeometryProcessor.cpp',
         'LogOptimizerState.cpp',
         'PDBOptimizerState.cpp',
         'PymolWriter.cpp',
         'Writer.cpp',
         'geometry.cpp',
         'particle_geometry.cpp',
        ] \
        + SConscript('internal/SConscript')

# Build and install the shared library:
env.IMPModuleLib(files)
