Import('env')

env.IMPModuleTest(python_tests= env.IMPModuleGetPythonTests(),
                  cpp_tests= env.IMPModuleGetCPPTests(),
                  show_exceptions=[# decorator, RefCounted arer just a base classes
                                   'Decorator', 'RefCounted',
                                   'PairFunctor', 'QuadFunctor', 'SingletonFunctor', 'TripletFunctor',
                      'PairDerivativeFunctor', 'QuadDerivativeFunctor', 'SingletonDerivativeFunctor', 'TripletDerivativeFunctor',
                                   'RandomNumberGenerator',
                                   # these are just constuctors for python tuples
                                   "ParticlePair", "ParticleTriplet", "ParticleQuad"],
                  function_name_exceptions=['Particle.has_attribute', 'Model.restore_particle',
                                            'RandomNumberGenerator.seed'],
                  value_object_exceptions=['Decorator', 'Exception','IOException', 'IndexException',
                                           'InternalException', 'ModelException', 'PairFunctor',
                                           'QuadFunctor', 'RandomNumberGenerator', 'RefCounted',
                                           'SingletonFunctor', 'TripletFunctor', 'UsageException',
                                           'PairDerivativeFunctor', 'QuadDerivativeFunctor',
                                           'SingletonDerivativeFunctor', 'TripletDerivativeFunctor',
                                           'ValueException', 'WarningContext', 'DerivativeAccumulator',
                                           # imported
                                           'FailureHandlerBase', 'FailureHandler', 'Object', 'SetLogState',
                                           'SetLogTarget'],
                  spelling_exceptions=['altgraph'])
