files = [
         'AttributeTable.h',
         'ExponentialNumber.h',
         'IndexingIterator.h',
         'NestedIterator.h',
         'OwnerPointer.h',
         'PrefixStream.h',
         'Unit.h',
         'Vector.h',
         'map.h',
         'attribute_storage.h',
         'constants.h',
         'container_helpers.h',
         'deprecation.h',
         'directories.h',
         'graph_utility.h',
         'ifile.h',
         'key_helpers.h',
         'particle.h',
         'particle_save.h',
         'ref_counting.h',
         'swig.h',
         'swig_helpers.h',
         'units.h',
         'utility.h',
        ]

files = [File(x) for x in files]
Return('files')
