Import('env')

files = [
         'AtomDecorator.h',
         'BondEndpointsRefiner.h',
         'BondPairContainer.h',
         'BondSingletonScore.h',
         'BrownianDynamics.h',
         'ChainDecorator.h',
         'DiffusionDecorator.h',
         'DomainDecorator.h',
         'MolecularDynamics.h',
         'MolecularHierarchyDecorator.h',
         'ResidueDecorator.h',
         'Topology.h',
         'VelocityScalingOptimizerState.h',
         'bond_decorators.h',
         'estimates.h',
         'macros.h',
         'pdb.h',
         'selectors.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPHeaders(files)
