Import('env')

files = [
         'Atom.h',
         'BondEndpointsRefiner.h',
         'BondPairContainer.h',
         'BondSingletonScore.h',
         'BrownianDynamics.h',
         'Chain.h',
         'CharmmParameters.h',
         'Diffusion.h',
         'Domain.h',
         'ForceFieldParameters.h',
         'Fragment.h',
         'Hierarchy.h',
         'MolecularDynamics.h',
         'Residue.h',
         'SimulationParameters.h',
         'VelocityScalingOptimizerState.h',
         'bond_decorators.h',
         'bond_graph.h',
         'estimates.h',
         'force_fields.h',
         'macros.h',
         'pdb.h',
         'selectors.h',
         'distance.h',
        ] \
        + SConscript('internal/SConscript')

# Install the include files:
env.IMPHeaders(files)
