name: CI
on: [push, pull_request]

jobs:
  test:
    name: "Python ${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          python-version: "3.10"
          cxxflags: "-fprofile-arcs -ftest-coverage"
          cgaldir: /usr/lib/x86_64-linux-gnu/cmake/CGAL/
        - os: macos-latest
          python-version: "3.13"
          cxxflags: ""
          cgaldir: ""
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libboost-all-dev swig libhdf5-dev libeigen3-dev \
            cmake libcgal-dev libcgal-qt5-dev libcereal-dev \
            libfftw3-dev libopencv-dev libgsl-dev libann-dev \
            libprotobuf-dev protobuf-compiler \
            libopenmpi-dev python3-dev python3-numpy python3-protobuf \
            python3-nose python3-pip python3-biopython
          pip3 install codecov
      - name: Install dependencies (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig boost cereal cmake cgal opencv gsl fftw eigen hdf5 protobuf numpy
          pip3 install codecov
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Set up git
        run: ./setup_git.py
      - name: Build IMP
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${{ matrix.cxxflags }}" -DCGAL_DIR="${{ matrix.cgaldir }}"
          make -k -j 2
          cd ..
      - name: Test IMP
        run: |
          cd build
          IMP_SKIP_UNSTABLE_TESTS=1 ctest --output-on-failure -L '\-tests?-' -E 'expensive|medium|IMP\.modeller\-' -T Test
          ctest --output-on-failure -R medium_test_standards -T Test
