name: CI
on: [push, pull_request]

jobs:
  test:
    name: "Python ${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          python-version: "3.10"
          cxxflags: "--coverage"
          linkflags: "--coverage"
          cgaldir: "/usr/lib/x86_64-linux-gnu/cmake/CGAL/"
          skiptests: "expensive|medium|IMP\\.modeller\\-"
        - os: ubuntu-24.04
          python-version: "3.12"
          cxxflags: "--coverage"
          linkflags: "--coverage"
          cgaldir: "/usr/lib/x86_64-linux-gnu/cmake/CGAL/"
          skiptests: "expensive|medium|IMP\\.modeller\\-"
        - os: macos-latest
          python-version: "3.13"
          cxxflags: "-std=c++17 --coverage"
          linkflags: "--coverage"
          cgaldir: "/opt/homebrew/lib/cmake/CGAL/"
          skiptests: "expensive|medium|IMP\\.modeller\\-|IMP\\.parallel\\-test_tasks|IMP\\.parallel\\-test_startup"
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libboost-all-dev swig libhdf5-dev libeigen3-dev \
            cmake libcgal-dev libcgal-qt5-dev libcereal-dev \
            libfftw3-dev libopencv-dev libgsl-dev libann-dev \
            libprotobuf-dev protobuf-compiler \
            libopenmpi-dev python3-dev python3-numpy python3-protobuf \
            python3-nose python3-pip python3-biopython
          pip3 install codecov
      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig boost cereal cgal opencv gsl fftw eigen hdf5 protobuf
          pip install codecov numpy
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Set up git
        run: ./setup_git.py
      - name: Build IMP
        run: |
          mkdir build
          cd build
          PYTHONPATH=`pwd`/coverage cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${{ matrix.cxxflags }}" -DCGAL_DIR="${{ matrix.cgaldir }}" -DCMAKE_LINKER_FLAGS="${{ matrix.linkflags }}"
          make -k -j 2
          cd ..
      - name: Test IMP
        run: |
          cd build
          ../tools/coverage/setup.py
          IMP_SKIP_UNSTABLE_TESTS=1 PYTHONPATH=`pwd`/coverage ctest --output-on-failure -L '\-tests?-' -E "${{ matrix.skiptests }}" -T Test
          ctest --output-on-failure -R medium_test_standards -E 'IMP\.modeller\-' -T Test
      - name: Combine coverage
        run: |
          cd build/coverage
          coverage combine && coverage xml && mv coverage.xml ../..
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
