Import('env')

env.IMPModuleTest(python_tests=env.IMPModuleGetPythonTests(),
                  cpp_tests=env.IMPModuleGetCPPTests(),
                  expensive_python_tests=env.IMPModuleGetExpensivePythonTests(),
                  show_exceptions=[],
                  value_object_exceptions=[],
                  function_name_exceptions=['AlignSymmetric.score_alignment',
                                      'CnSymmAxisDetector.calc_symm_score',
                                      'MolCnSymmAxisDetector.calc_symm_score'],
                  spelling_exceptions=['pca', 'cn', 'symm', 'symmetrics'])
